import {useEffect,useState} from 'react';
import {useAuth} from './AuthContext';
import {supabase} from '../lib/supabase';
import {listRecords} from '../lib/workspace';
import {modules,fieldsFor,metrics} from '../lib/modules';
import {canAccessPage} from '../lib/rbac';
import {generateExport} from '../lib/export';
import {Charts} from './WorkspaceModule';
import SmartSelect from './SmartSelect';
export default function ExportCenter({t,reports=false}){
 const {user}=useAuth(),ar=t.dir==='rtl',available=Object.keys(modules).filter(k=>canAccessPage(user,k));
 const [module,setModule]=useState(available[0]||''),[rows,setRows]=useState([]),[error,setError]=useState(''),[loading,setLoading]=useState(false),[format,setFormat]=useState('xlsx'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[department,setDepartment]=useState(''),[busy,setBusy]=useState(false),[history,setHistory]=useState([]);
 const historyLoad=()=>supabase.from('export_history').select('*').order('created_at',{ascending:false}).limit(30).then(({data,error})=>{if(error)setError(error.message);else setHistory(data||[])});
 useEffect(()=>{if(!module)return;let alive=true;setLoading(true);setError('');listRecords(module).then(data=>{if(alive)setRows(data)}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[module]);
 useEffect(()=>{if(!reports)historyLoad()},[reports]);
 const filtered=rows.filter(r=>(!department||r.department===department)&&(!from||String(r[modules[module].date]||'').slice(0,10)>=from)&&(!to||String(r[modules[module].date]||'').slice(0,10)<=to));
 const exportAllowed=canAccessPage(user,'exports')&&(user.role==='company_admin'||format==='csv'||user.export_permissions?.[format])&&(module!=='purchasing'||user.role==='company_admin'||user.export_permissions?.financial);
 const run=async()=>{setBusy(true);setError('');try{if(!exportAllowed)throw new Error('Export permission required');const name=`net-expert-${module}-${Date.now()}`,data=filtered.map(r=>Object.fromEntries(fieldsFor(module).map(f=>[ar?f.ar:f.en,r[f.key]??''])));const size=await generateExport({rows:data,format,fileName:name,organization:user.organization_name,user:user.name||user.email,title:modules[module][ar?'ar':'en'],rtl:ar});const {error}=await supabase.from('export_history').insert({file_name:`${name}.${format}`,file_type:format,source:module,record_count:data.length,file_size:size,filters:{from,to,department},exported_by:user.id});if(error)throw new Error((ar?'تم إنشاء الملف، لكن تعذر حفظ السجل: ':'File generated, but history could not be saved: ')+error.message);await historyLoad()}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <div className="work-page"><header className="work-heading"><div><small>{user.organization_name}</small><h1>{reports?(ar?'التقارير':'Reports'):(ar?'مركز التصدير':'Export Center')}</h1><p>{ar?'تقارير من سجلات الشركة، مع احترام صلاحيات الوحدات.':'Company records, with module access respected.'}</p></div></header><div className="work-tabs">{available.map(key=><button key={key} className={module===key?'active':''} onClick={()=>setModule(key)}>{modules[key][ar?'ar':'en']}</button>)}</div>{!available.length?<p>{ar?'لا توجد مصادر مسموحة':'No permitted data sources'}</p>:<><div className="work-filters"><SmartSelect list="department" ar={ar} label={ar?'القسم':'Department'} value={department} onChange={setDepartment} creatable={false}/><label>{ar?'من':'From'}<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>{ar?'إلى':'To'}<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={()=>{setFrom('');setTo('');setDepartment('')}}>{ar?'مسح':'Clear'}</button></div>{error&&<p role="alert" className="work-error">{error}</p>}{loading?<p role="status">{ar?'جارٍ التحميل…':'Loading…'}</p>:reports?<><div className="work-metrics">{metrics(module,filtered).map(([en,arabic,n])=><section key={en}><span>{ar?arabic:en}</span><strong>{n.toLocaleString()}</strong></section>)}</div><Charts module={module} rows={filtered} ar={ar}/></>:<section className="work-export"><h2>{filtered.length} {ar?'سجل جاهز للتصدير':'records ready to export'}</h2><div className="work-tabs">{['xlsx','csv','pdf'].map(x=><button aria-pressed={format===x} className={format===x?'active':''} key={x} onClick={()=>setFormat(x)}>{x.toUpperCase()}</button>)}</div>{format==='pdf'&&<p>{ar?'يفتح التقرير للطباعة؛ اختر حفظ بصيغة PDF.':'Opens a print report. Choose Save as PDF.'}</p>}<button className="work-primary" disabled={busy||!exportAllowed} onClick={run}>{busy?(ar?'جارٍ الإنشاء…':'Generating…'):(ar?'إنشاء الملف':'Generate file')}</button>{!exportAllowed&&<p>{ar?'تحتاج صلاحية تصدير من مسؤول الشركة.':'Your company administrator must grant export access.'}</p>}<h2>{ar?'سجل التصدير':'Export history'}</h2><div className="work-grid"><table><thead><tr>{(ar?['الملف','النوع','السجلات','الحجم','التاريخ']:['File','Format','Records','Size','Date']).map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{history.filter(r=>['sim','assets','purchasing'].includes(r.source)).map(r=><tr key={r.id}><td>{r.file_name}</td><td>{r.file_type}</td><td>{r.record_count}</td><td>{Math.ceil((r.file_size||0)/1024)} KB</td><td>{new Date(r.created_at).toLocaleString()}</td></tr>)}</tbody></table></div></section>}</>}</div>
}
