import {useEffect,useMemo,useRef,useState} from 'react';
import {fieldsFor,modules} from '../lib/modules';
import {buildImportRows,duplicateIdentity,importFields,matchExcelColumns,parseImportText} from '../lib/excel-import';
import {bulkImportRecords,listRecords} from '../lib/workspace';
import {can} from '../lib/rbac';
const labels={employee_id:['Employee ID','الرقم الوظيفي'],employee_name:['Employee Name','اسم الموظف'],email_address:['Email Address','البريد الإلكتروني'],department:['Department','القسم'],assign_location:['Location','الموقع'],mobile_number:['Mobile Number','رقم الجوال'],sim_number:['SIM Number','رقم الشريحة'],account_number:['Account Number','رقم الحساب'],provider:['Provider','المزود'],sim_package:['SIM Package','الباقة'],date_issued:['Date Issued','تاريخ التسليم'],date_returned:['Date Returned','تاريخ الإرجاع'],hardware:['Hardware Type','نوع الأصل'],brand:['Brand','العلامة'],model:['Asset Name / Model','اسم الأصل / الموديل'],serial_number:['Serial Number','الرقم التسلسلي'],asset_tag:['Asset Tag','رمز الأصل'],warranty_start:['Warranty Start','بداية الضمان'],warranty_end:['Warranty End','نهاية الضمان'],status:['Status','الحالة'],notes:['Notes','ملاحظات']};
let tesseractLoader;
const loadTesseract=()=>{if(typeof window==='undefined')return Promise.reject(new Error('OCR is available in the browser only'));if(window.Tesseract)return Promise.resolve(window.Tesseract);if(!tesseractLoader)tesseractLoader=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/tesseract.js@7.0.0/dist/tesseract.min.js';script.crossOrigin='anonymous';script.onload=()=>window.Tesseract?resolve(window.Tesseract):reject(new Error('OCR library did not load'));script.onerror=()=>reject(new Error('Unable to load the image reader'));document.head.appendChild(script)});return tesseractLoader};
export default function ImportCenter({user,ar,onClose}){
 const permitted=['sim','assets'].filter(module=>can(user,'write',module));
 const [headers,setHeaders]=useState([]),[raw,setRaw]=useState([]),[mapping,setMapping]=useState({}),[sheet,setSheet]=useState(''),[fileName,setFileName]=useState(''),[preview,setPreview]=useState([]),[duplicates,setDuplicates]=useState(new Set()),[policy,setPolicy]=useState('skip'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState(0),[summary,setSummary]=useState(null),[source,setSource]=useState('excel'),[pastedText,setPastedText]=useState(''),[imageUrl,setImageUrl]=useState(''),[forcedModule,setForcedModule]=useState('auto'),[rowOffset,setRowOffset]=useState(2);const worker=useRef(null),ocrWorker=useRef(null);
 useEffect(()=>()=>{worker.current?.terminate();ocrWorker.current?.terminate?.();if(imageUrl)URL.revokeObjectURL(imageUrl)},[imageUrl]);const rows=useMemo(()=>buildImportRows(raw,mapping,forcedModule,rowOffset),[raw,mapping,forcedModule,rowOffset]);const targets=useMemo(()=>({sim:rows.filter(r=>r.module==='sim').length,assets:rows.filter(r=>r.module==='assets').length,unknown:raw.length-rows.length}),[rows,raw]);const relevant=new Set(rows.length?rows.flatMap(item=>fieldsFor(item.module).map(field=>field.key)):forcedModule==='sim'||forcedModule==='assets'?fieldsFor(forcedModule).map(field=>field.key):importFields),matched=importFields.filter(key=>mapping[key]!==undefined&&relevant.has(key)),missing=importFields.filter(key=>mapping[key]===undefined&&relevant.has(key));
 const resetResults=()=>{setError('');setSummary(null);setPreview([]);setHeaders([]);setRaw([]);setMapping({});setFileName('');setSheet('');setRowOffset(2)};
 const applyParsed=(result,name,origin)=>{if(!result.headers.length||!result.rows.length)throw new Error(ar?'تعذر اكتشاف جدول. استخدم صف عناوين ثم الصق البيانات، أو استخدم صيغة «الحقل: القيمة».':'No table was detected. Include a header row, or use “field: value” lines.');setHeaders(result.headers);setRaw(result.rows);setMapping(matchExcelColumns(result.headers));setSheet(origin);setFileName(name);setRowOffset(2);setProgress(35)};
 const readFile=async file=>{if(!file)return;setError('');setSummary(null);setPreview([]);if(!/\.(xlsx|xls)$/i.test(file.name)){setError(ar?'اختر ملف Excel بصيغة xlsx أو xls.':'Choose an .xlsx or .xls workbook.');return}if(file.size>20*1024*1024){setError(ar?'الحد الأقصى 20 MB.':'Maximum file size is 20 MB.');return}setBusy(true);setProgress(10);try{worker.current?.terminate();const w=new Worker(new URL('../workers/import.worker.js',import.meta.url));worker.current=w;const result=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{w.terminate();reject(new Error('Workbook parsing timed out'))},60000);w.onmessage=e=>{clearTimeout(timer);e.data.error?reject(new Error(e.data.error)):resolve(e.data)};w.onerror=()=>{clearTimeout(timer);reject(new Error('Unable to read this workbook'))};file.arrayBuffer().then(buffer=>w.postMessage(buffer,[buffer])).catch(reject)});w.terminate();setHeaders(result.headers);setRaw(result.rows);setMapping(matchExcelColumns(result.headers));setSheet(`${result.sheetName} · ${ar?'صف العناوين':'header row'} ${result.headerRow}`);setFileName(file.name);setRowOffset(result.headerRow+1);setProgress(35)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const analyzeText=()=>{resetResults();try{applyParsed(parseImportText(pastedText),ar?'بيانات ملصقة':'Pasted data',ar?'نسخ ولصق':'Copy & paste')}catch(e){setError(e.message)}};
 const readImage=async file=>{if(!file)return;if(!/^image\/(png|jpeg|webp)$/i.test(file.type)){setError(ar?'اختر صورة PNG أو JPG أو WebP.':'Choose a PNG, JPG, or WebP image.');return}if(file.size>10*1024*1024){setError(ar?'الحد الأقصى للصورة 10 MB.':'Maximum image size is 10 MB.');return}resetResults();if(imageUrl)URL.revokeObjectURL(imageUrl);setImageUrl(URL.createObjectURL(file));setBusy(true);setProgress(5);try{const Tesseract=await loadTesseract();const created=await Tesseract.createWorker(['ara','eng'],1,{logger:message=>{if(message.status==='recognizing text')setProgress(15+Math.round((message.progress||0)*70))}});ocrWorker.current=created;const result=await created.recognize(file);await created.terminate();ocrWorker.current=null;const text=result?.data?.text?.trim()||'';setPastedText(text);applyParsed(parseImportText(text),file.name,ar?'صورة OCR':'OCR image');setProgress(90)}catch(e){setError(`${ar?'تعذر قراءة الصورة':'Unable to read image'}: ${e.message}`)}finally{setBusy(false)}};
 const handleClipboardImage=e=>{const file=[...(e.clipboardData?.files||[])].find(item=>item.type.startsWith('image/'));if(file){e.preventDefault();setSource('image');readImage(file)}};
 const prepare=async()=>{setBusy(true);setError('');setProgress(45);try{const existing=(await Promise.all(permitted.map(async module=>[module,await listRecords(module)]))).flatMap(([module,records])=>records.map(record=>({module,keys:module==='sim'?[record.employee_id,record.sim_number]:[record.asset_tag,record.employee_id,record.serial_number]}))),known=new Set(existing.flatMap(item=>item.keys.filter(Boolean).map(key=>`${item.module}:${String(key).trim().toLowerCase()}`))),found=new Set();for(const item of rows){if(!permitted.includes(item.module))continue;for(const key of duplicateIdentity(item)){const token=`${item.module}:${String(key).trim().toLowerCase()}`;if(known.has(token)||found.has(token))found.add(`row:${item.row}`);else found.add(token)}}setDuplicates(found);setPreview(rows);setProgress(60)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const execute=async()=>{setBusy(true);setError('');setProgress(70);try{const result=await bulkImportRecords(preview.filter(item=>permitted.includes(item.module)),policy);setProgress(100);setSummary(result);setPreview([])}catch(e){setError(e.message)}finally{setBusy(false)}};
 if(!permitted.length)return <section className="import-center"><p className="work-error">{ar?'لا تملك صلاحية الاستيراد.':'You do not have import permission.'}</p></section>;
 return <section className="import-center" aria-labelledby="excel-import-title" onPaste={handleClipboardImage}><header><div><small>DATA IMPORT</small><h2 id="excel-import-title">{ar?'استيراد البيانات':'Import data'}</h2><p>{ar?'من Excel أو النسخ واللصق أو صورة، مع توزيع تلقائي للسجلات.':'From Excel, copy and paste, or an image, with automatic record routing.'}</p></div>{onClose&&<button onClick={onClose} aria-label="Close">×</button>}</header><div className="import-body"><nav className="import-sources" aria-label={ar?'مصدر البيانات':'Data source'}>{[['excel',ar?'ملف Excel':'Excel file'],['paste',ar?'نسخ ولصق':'Copy & paste'],['image',ar?'صورة':'Image']].map(([key,label])=><button type="button" className={source===key?'active':''} onClick={()=>{setSource(key);resetResults()}} key={key}>{label}</button>)}</nav>
 {source==='excel'&&<label className="import-drop"><input type="file" accept=".xlsx,.xls" disabled={busy} onChange={e=>readFile(e.target.files?.[0])}/><b>{fileName||(ar?'اختر ملف Excel':'Choose an Excel workbook')}</b><span>.xlsx / .xls · 20 MB · 20,000 {ar?'صف':'rows'}</span></label>}
 {source==='paste'&&<div className="import-paste"><label>{ar?'الصق جدولاً من Excel أو نصاً بصيغة «الحقل: القيمة»':'Paste an Excel table or “field: value” text'}<textarea dir="auto" value={pastedText} onChange={e=>setPastedText(e.target.value)} placeholder={ar?'الرقم الوظيفي\tاسم الموظف\tرقم الشريحة\n100657\tSAMEH KAMIL\t831046001396':'Employee ID\tEmployee Name\tSIM Number\n100657\tSAMEH KAMIL\t831046001396'}/></label><button className="work-primary" disabled={busy||!pastedText.trim()} onClick={analyzeText}>{ar?'تحليل البيانات الملصقة':'Analyze pasted data'}</button></div>}
 {source==='image'&&<div className="import-image"><label className="import-drop"><input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>readImage(e.target.files?.[0])}/><b>{fileName||(ar?'ارفع صورة أو الصقها هنا':'Upload or paste an image here')}</b><span>PNG / JPG / WebP · 10 MB · OCR عربي + English</span></label>{imageUrl&&<img src={imageUrl} alt={ar?'معاينة الصورة المرفوعة':'Uploaded image preview'}/>}<label>{ar?'النص المستخرج — يمكنك تصحيحه ثم إعادة التحليل':'Extracted text — edit it, then analyze again'}<textarea dir="auto" value={pastedText} onChange={e=>setPastedText(e.target.value)}/></label>{pastedText&&<button className="work-primary" disabled={busy} onClick={analyzeText}>{ar?'إعادة تحليل النص':'Analyze corrected text'}</button>}</div>}
 {busy&&<div className="import-progress" role="status"><i style={{width:`${progress}%`}}/><span>{source==='image'?(ar?'جارٍ استخراج النص…':'Reading image…'):(ar?'جارٍ المعالجة…':'Processing…')} {progress}%</span></div>}{error&&<p className="work-error" role="alert">{error}</p>}
 {headers.length>0&&<><div className="import-summary"><div><span>{ar?'السجلات المكتشفة':'Detected rows'}</span><strong>{raw.length.toLocaleString()}</strong></div><div><span>{ar?'عهد SIM':'SIM Custody'}</span><strong>{targets.sim}</strong></div><div><span>{ar?'الأصول التقنية':'IT Assets'}</span><strong>{targets.assets}</strong></div><div><span>{ar?'غير مصنفة':'Unclassified'}</span><strong>{targets.unknown}</strong></div></div><p className="work-muted">{fileName} · {sheet}</p><label className="import-route">{ar?'وجهة السجلات':'Record destination'}<select value={forcedModule} onChange={e=>setForcedModule(e.target.value)}><option value="auto">{ar?'تلقائي حسب البيانات':'Automatic detection'}</option>{permitted.includes('sim')&&<option value="sim">{ar?'عهد شرائح SIM':'SIM Custody'}</option>}{permitted.includes('assets')&&<option value="assets">{ar?'الأصول التقنية':'IT Assets'}</option>}</select><small>{ar?'استخدم الاختيار اليدوي إذا كانت البيانات لا تحتوي رقم شريحة أو رقم تسلسلي.':'Choose manually when the file has no SIM or serial-number signals.'}</small></label><div className="import-matches"><section><h3>{ar?'الحقول المطابقة':'Matched fields'}</h3>{matched.map(key=><span className="matched" key={key}>✓ {labels[key][ar?1:0]} <small>← {headers[mapping[key]]}</small></span>)}</section><section><h3>{ar?'الحقول المفقودة':'Missing fields'}</h3>{missing.map(key=><span className="missing" key={key}>⚠ {labels[key][ar?1:0]}</span>)}</section></div><details className="import-mapping" open={!matched.length}><summary>{ar?'مراجعة مطابقة الأعمدة':'Review column mapping'}</summary><div>{importFields.filter(key=>relevant.has(key)).map(key=><label key={key}>{labels[key][ar?1:0]}<select value={mapping[key]??''} onChange={e=>setMapping(current=>{const next={...current};if(e.target.value==='')delete next[key];else next[key]=Number(e.target.value);return next})}><option value="">{ar?'غير مطابق':'Not mapped'}</option>{headers.map((header,index)=><option key={index} value={index}>{header}</option>)}</select></label>)}</div></details><button className="work-primary" disabled={busy||!rows.length} onClick={prepare}>{ar?'معاينة السجلات':'Preview records'}</button></>}
 {preview.length>0&&<><div className="import-confirm"><label>{ar?'عند وجود سجل مكرر':'When a duplicate is found'}<select value={policy} onChange={e=>setPolicy(e.target.value)}><option value="skip">{ar?'تخطي السجل الموجود':'Skip existing record'}</option><option value="update">{ar?'تحديث بالبيانات الجديدة':'Update with imported data'}</option></select></label><p>{ar?'الكشف بالرقم الوظيفي أو رقم الشريحة أو Asset Tag أو الرقم التسلسلي.':'Detected by employee ID, SIM number, asset tag, or serial number.'}</p></div><div className="work-grid import-preview"><table><thead><tr><th>{ar?'الصف':'Row'}</th><th>{ar?'الوجهة':'Destination'}</th><th>{ar?'الموظف':'Employee'}</th><th>{ar?'المعرّف':'Identifier'}</th><th>{ar?'الحالة':'State'}</th></tr></thead><tbody>{preview.slice(0,100).map(item=><tr key={item.row}><td>{item.row}</td><td>{modules[item.module][ar?'ar':'en']}</td><td>{item.data.employee_name||item.data.employee_id||'—'}</td><td>{item.data.sim_number||item.data.asset_tag||item.data.serial_number||'—'}</td><td>{!permitted.includes(item.module)?(ar?'بدون صلاحية':'No permission'):duplicates.has(`row:${item.row}`)?(ar?'مكرر':'Duplicate'):(ar?'جاهز':'Ready')}</td></tr>)}</tbody></table></div><p className="work-muted">{ar?'تظهر أول 100 نتيجة؛ سيتم تنفيذ جميع السجلات دفعة واحدة.':'First 100 shown; all eligible records run in one bulk operation.'}</p><button className="work-primary" disabled={busy} onClick={execute}>{ar?'تأكيد الاستيراد':'Confirm bulk import'}</button></>}
 {summary&&<div className="import-complete" role="status"><h3>{ar?'تم الاستيراد بنجاح':'Import completed'}</h3><p>✓ {summary.sim?.inserted||0} {ar?'سجل إلى عهد SIM':'SIM records'} · {summary.sim?.updated||0} {ar?'محدّث':'updated'}</p><p>✓ {summary.assets?.inserted||0} {ar?'سجل إلى الأصول التقنية':'asset records'} · {summary.assets?.updated||0} {ar?'محدّث':'updated'}</p><p>{ar?'تم تخطي':'Skipped'}: {summary.skipped||0} · {ar?'فشل':'Failed'}: {summary.failed||0}</p></div>}</div></section>;
}

