import {useEffect,useMemo,useRef,useState} from 'react';
import {fieldsFor,modules} from '../lib/modules';
import {buildImportRows,duplicateIdentity,importFields,matchExcelColumns} from '../lib/excel-import';
import {bulkImportRecords,listRecords} from '../lib/workspace';
import {can} from '../lib/rbac';
const labels={employee_id:['Employee ID','الرقم الوظيفي'],employee_name:['Employee Name','اسم الموظف'],email_address:['Email Address','البريد الإلكتروني'],department:['Department','القسم'],assign_location:['Location','الموقع'],mobile_number:['Mobile Number','رقم الجوال'],sim_number:['SIM Number','رقم الشريحة'],account_number:['Account Number','رقم الحساب'],provider:['Provider','المزود'],sim_package:['SIM Package','الباقة'],date_issued:['Date Issued','تاريخ التسليم'],date_returned:['Date Returned','تاريخ الإرجاع'],hardware:['Hardware Type','نوع الأصل'],brand:['Brand','العلامة'],model:['Asset Name / Model','اسم الأصل / الموديل'],serial_number:['Serial Number','الرقم التسلسلي'],asset_tag:['Asset Tag','رمز الأصل'],warranty_start:['Warranty Start','بداية الضمان'],warranty_end:['Warranty End','نهاية الضمان'],status:['Status','الحالة'],notes:['Notes','ملاحظات']};
export default function ImportCenter({user,ar,onClose}){
 const permitted=['sim','assets'].filter(module=>can(user,'write',module));
 const [headers,setHeaders]=useState([]),[raw,setRaw]=useState([]),[mapping,setMapping]=useState({}),[sheet,setSheet]=useState(''),[fileName,setFileName]=useState(''),[preview,setPreview]=useState([]),[duplicates,setDuplicates]=useState(new Set()),[policy,setPolicy]=useState('skip'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[progress,setProgress]=useState(0),[summary,setSummary]=useState(null);const worker=useRef(null);
 useEffect(()=>()=>worker.current?.terminate(),[]);const rows=useMemo(()=>buildImportRows(raw,mapping),[raw,mapping]);const targets=useMemo(()=>({sim:rows.filter(r=>r.module==='sim').length,assets:rows.filter(r=>r.module==='assets').length,unknown:raw.length-rows.length}),[rows,raw]);const relevant=new Set(rows.flatMap(item=>fieldsFor(item.module).map(field=>field.key))),matched=importFields.filter(key=>mapping[key]!==undefined&&relevant.has(key)),missing=importFields.filter(key=>mapping[key]===undefined&&relevant.has(key));
 const readFile=async file=>{if(!file)return;setError('');setSummary(null);setPreview([]);if(!/\.(xlsx|xls)$/i.test(file.name)){setError(ar?'اختر ملف Excel بصيغة xlsx أو xls.':'Choose an .xlsx or .xls workbook.');return}if(file.size>20*1024*1024){setError(ar?'الحد الأقصى 20 MB.':'Maximum file size is 20 MB.');return}setBusy(true);setProgress(10);try{worker.current?.terminate();const w=new Worker(new URL('../workers/import.worker.js',import.meta.url));worker.current=w;const result=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{w.terminate();reject(new Error('Workbook parsing timed out'))},60000);w.onmessage=e=>{clearTimeout(timer);e.data.error?reject(new Error(e.data.error)):resolve(e.data)};w.onerror=()=>{clearTimeout(timer);reject(new Error('Unable to read this workbook'))};file.arrayBuffer().then(buffer=>w.postMessage(buffer,[buffer])).catch(reject)});w.terminate();setHeaders(result.headers);setRaw(result.rows);setMapping(matchExcelColumns(result.headers));setSheet(result.sheetName);setFileName(file.name);setProgress(35)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const prepare=async()=>{setBusy(true);setError('');setProgress(45);try{const existing=(await Promise.all(permitted.map(async module=>[module,await listRecords(module)]))).flatMap(([module,records])=>records.map(record=>({module,keys:module==='sim'?[record.employee_id,record.sim_number]:[record.asset_tag,record.employee_id,record.serial_number]}))),known=new Set(existing.flatMap(item=>item.keys.filter(Boolean).map(key=>`${item.module}:${String(key).trim().toLowerCase()}`))),found=new Set();for(const item of rows){if(!permitted.includes(item.module))continue;for(const key of duplicateIdentity(item)){const token=`${item.module}:${String(key).trim().toLowerCase()}`;if(known.has(token)||found.has(token))found.add(`row:${item.row}`);else found.add(token)}}setDuplicates(found);setPreview(rows);setProgress(60)}catch(e){setError(e.message)}finally{setBusy(false)}};
 const execute=async()=>{setBusy(true);setError('');setProgress(70);try{const result=await bulkImportRecords(preview.filter(item=>permitted.includes(item.module)),policy);setProgress(100);setSummary(result);setPreview([])}catch(e){setError(e.message)}finally{setBusy(false)}};
 if(!permitted.length)return <section className="import-center"><p className="work-error">{ar?'لا تملك صلاحية الاستيراد.':'You do not have import permission.'}</p></section>;
 return <section className="import-center" aria-labelledby="excel-import-title"><header><div><small>EXCEL IMPORT</small><h2 id="excel-import-title">{ar?'استيراد Excel':'Import Excel'}</h2><p>{ar?'توزيع تلقائي إلى عهد SIM أو الأصول التقنية.':'Automatic routing to SIM Custody or IT Assets.'}</p></div>{onClose&&<button onClick={onClose} aria-label="Close">×</button>}</header><div className="import-body"><label className="import-drop"><input type="file" accept=".xlsx,.xls" disabled={busy} onChange={e=>readFile(e.target.files?.[0])}/><b>{fileName||(ar?'اختر ملف Excel':'Choose an Excel workbook')}</b><span>.xlsx / .xls · 20 MB · 20,000 {ar?'صف':'rows'}</span></label>{busy&&<div className="import-progress" role="status"><i style={{width:`${progress}%`}}/><span>{ar?'جارٍ المعالجة…':'Processing…'} {progress}%</span></div>}{error&&<p className="work-error" role="alert">{error}</p>}
 {headers.length>0&&<><div className="import-summary"><div><span>{ar?'السجلات المكتشفة':'Detected rows'}</span><strong>{raw.length.toLocaleString()}</strong></div><div><span>{ar?'عهد SIM':'SIM Custody'}</span><strong>{targets.sim}</strong></div><div><span>{ar?'الأصول التقنية':'IT Assets'}</span><strong>{targets.assets}</strong></div><div><span>{ar?'غير مصنفة':'Unclassified'}</span><strong>{targets.unknown}</strong></div></div><p className="work-muted">{fileName} · {sheet}</p><div className="import-matches"><section><h3>{ar?'الحقول المطابقة':'Matched fields'}</h3>{matched.map(key=><span className="matched" key={key}>✓ {labels[key][ar?1:0]} <small>← {headers[mapping[key]]}</small></span>)}</section><section><h3>{ar?'الحقول المفقودة':'Missing fields'}</h3>{missing.map(key=><span className="missing" key={key}>⚠ {labels[key][ar?1:0]}</span>)}</section></div><details className="import-mapping"><summary>{ar?'مراجعة مطابقة الأعمدة':'Review column mapping'}</summary><div>{importFields.filter(key=>relevant.has(key)).map(key=><label key={key}>{labels[key][ar?1:0]}<select value={mapping[key]??''} onChange={e=>setMapping(current=>{const next={...current};if(e.target.value==='')delete next[key];else next[key]=Number(e.target.value);return next})}><option value="">{ar?'غير مطابق':'Not mapped'}</option>{headers.map((header,index)=><option key={index} value={index}>{header}</option>)}</select></label>)}</div></details><button className="work-primary" disabled={busy||!rows.length} onClick={prepare}>{ar?'معاينة السجلات':'Preview records'}</button></>}
 {preview.length>0&&<><div className="import-confirm"><label>{ar?'عند وجود سجل مكرر':'When a duplicate is found'}<select value={policy} onChange={e=>setPolicy(e.target.value)}><option value="skip">{ar?'تخطي السجل الموجود':'Skip existing record'}</option><option value="update">{ar?'تحديث بالبيانات الجديدة':'Update with imported data'}</option></select></label><p>{ar?'الكشف بالرقم الوظيفي أو رقم الشريحة أو Asset Tag أو الرقم التسلسلي.':'Detected by employee ID, SIM number, asset tag, or serial number.'}</p></div><div className="work-grid import-preview"><table><thead><tr><th>{ar?'الصف':'Row'}</th><th>{ar?'الوجهة':'Destination'}</th><th>{ar?'الموظف':'Employee'}</th><th>{ar?'المعرّف':'Identifier'}</th><th>{ar?'الحالة':'State'}</th></tr></thead><tbody>{preview.slice(0,100).map(item=><tr key={item.row}><td>{item.row}</td><td>{modules[item.module][ar?'ar':'en']}</td><td>{item.data.employee_name||item.data.employee_id||'—'}</td><td>{item.data.sim_number||item.data.asset_tag||item.data.serial_number||'—'}</td><td>{!permitted.includes(item.module)?(ar?'بدون صلاحية':'No permission'):duplicates.has(`row:${item.row}`)?(ar?'مكرر':'Duplicate'):(ar?'جاهز':'Ready')}</td></tr>)}</tbody></table></div><p className="work-muted">{ar?'تظهر أول 100 نتيجة؛ سيتم تنفيذ جميع السجلات دفعة واحدة.':'First 100 shown; all eligible records run in one bulk operation.'}</p><button className="work-primary" disabled={busy} onClick={execute}>{ar?'تأكيد الاستيراد':'Confirm bulk import'}</button></>}
 {summary&&<div className="import-complete" role="status"><h3>{ar?'تم الاستيراد بنجاح':'Import completed'}</h3><p>✓ {summary.sim?.inserted||0} {ar?'سجل إلى عهد SIM':'SIM records'} · {summary.sim?.updated||0} {ar?'محدّث':'updated'}</p><p>✓ {summary.assets?.inserted||0} {ar?'سجل إلى الأصول التقنية':'asset records'} · {summary.assets?.updated||0} {ar?'محدّث':'updated'}</p><p>{ar?'تم تخطي':'Skipped'}: {summary.skipped||0} · {ar?'فشل':'Failed'}: {summary.failed||0}</p></div>}</div></section>;
}
