import { useState } from 'react';
import { useAuth } from './AuthContext';

const capabilities=[{en:'Asset visibility',ar:'رؤية موحدة للأصول'},{en:'Operational control',ar:'ضبط العمليات'},{en:'Lifecycle governance',ar:'حوكمة دورة الحياة'}];
function ProductMark(){return <span className="login-product-mark" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M5 7.5 12 3.5l7 4v8l-7 4-7-4v-8Z"/><path d="m5 7.5 7 4 7-4M12 11.5v8"/></svg></span>}

export default function LoginPage({t}){
 const auth=useAuth(),ar=t.dir==='rtl';
 const [mode,setMode]=useState(auth.recoveryMode?'newPassword':'login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[fullName,setFullName]=useState(''),[remember,setRemember]=useState(true),[loading,setLoading]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const copy={login:[ar?'تسجيل الدخول':'Sign in',ar?'استخدم حساب Net Expert الخاص بمؤسستك.':'Use your organization Net Expert account.'],signup:[ar?'إنشاء حساب':'Create account',ar?'يبدأ الحساب الجديد بصلاحية مشاهد.':'New accounts start with Viewer access.'],forgot:[ar?'استعادة الحساب':'Recover account',ar?'سنرسل رابطاً آمناً لتعيين كلمة مرور جديدة.':'We will send a secure link to set a new password.'],activation:[ar?'إعادة إرسال التفعيل':'Resend activation',ar?'أدخل بريد الحساب لإرسال رابط تفعيل جديد.':'Enter your account email to receive a new activation link.'],newPassword:[ar?'كلمة مرور جديدة':'Set a new password',ar?'اختر كلمة مرور قوية لحسابك.':'Choose a strong password for your account.']};
 const go=next=>{setMode(next);setError('');setMessage('');setPassword('');setConfirm('')};
 const friendly=e=>{const msg=(e?.message||'').toLowerCase(),code=e?.code||'';if(e?.message==='ACCOUNT_SUSPENDED')return ar?'الحساب موقوف. تواصل مع مسؤول النظام.':'This account is suspended. Contact your administrator.';if(e?.message==='ACCOUNT_EXISTS'||code==='user_already_exists'||msg.includes('already registered')||msg.includes('already exists'))return ar?'البريد مستخدم مسبقاً. سجل الدخول أو استعد كلمة المرور.':'This email is already in use. Sign in or recover your password.';if(code==='email_not_confirmed'||msg.includes('email not confirmed'))return ar?'الحساب غير مفعّل. افتح رابط التفعيل المرسل إلى بريدك.':'Your account is not activated. Open the activation link sent to your email.';if(code==='email_address_invalid'||msg.includes('invalid email'))return ar?'عنوان البريد الإلكتروني غير صالح.':'Enter a valid email address.';if(e?.status===429||code==='over_email_send_rate_limit'||msg.includes('rate limit'))return ar?'تم تجاوز عدد المحاولات المسموح. انتظر قليلاً ثم حاول مجدداً.':'Too many attempts. Please wait and try again.';if(code==='invalid_credentials'||msg.includes('invalid login credentials'))return ar?'البريد الإلكتروني أو كلمة المرور غير صحيحة.':'The email address or password is incorrect.';if(code==='weak_password'||msg.includes('password'))return ar?'كلمة المرور قصيرة أو ضعيفة. استخدم 8 أحرف على الأقل.':'The password is too short or weak. Use at least 8 characters.';if(msg.includes('fetch')||msg.includes('network')||e?.status===0)return ar?'خطأ اتصال. تحقق من الشبكة وحاول مجدداً.':'Connection error. Check your network and try again.';return ar?`تعذر إكمال الطلب: ${e?.message||'خطأ غير معروف'}`:`Could not complete the request: ${e?.message||'Unknown error'}`};
 const submit=async e=>{e.preventDefault();setLoading(true);setError('');setMessage('');try{const normalized=email.trim().toLowerCase();if(mode==='login')await auth.login(normalized,password,remember);if(mode==='signup'){if(password.length<8)throw new Error('SHORT');if(password!==confirm)throw new Error('MATCH');const result=await auth.signUp({fullName:fullName.trim(),email:normalized,password});if(result.confirmationRequired){setMode('sent');setMessage(ar?'أرسلنا رابط التفعيل إلى بريدك. افتح الرسالة لتفعيل الحساب ثم سجل الدخول.':'We sent an activation link to your email. Activate your account, then sign in.')}}if(mode==='forgot'){await auth.requestPasswordReset(normalized);setMode('sent');setMessage(ar?'أرسلنا رابط استعادة الحساب إذا كان البريد مسجلاً.':'If the email is registered, a recovery link has been sent.')}if(mode==='activation'){await auth.resendActivation(normalized);setMode('sent');setMessage(ar?'تم إرسال رابط تفعيل جديد.':'A new activation link has been sent.')}if(mode==='newPassword'){if(password.length<8)throw new Error('SHORT');if(password!==confirm)throw new Error('MATCH');await auth.updatePassword(password);setMode('login');setMessage(ar?'تم تحديث كلمة المرور. يمكنك المتابعة الآن.':'Your password has been updated. You can continue now.')}}catch(ex){setError(ex.message==='SHORT'?(ar?'استخدم 8 أحرف على الأقل.':'Use at least 8 characters.'):ex.message==='MATCH'?(ar?'كلمتا المرور غير متطابقتين.':'Passwords do not match.'):friendly(ex))}finally{setLoading(false)}};
 const title=mode==='sent'?(ar?'تحقق من بريدك':'Check your email'):(copy[mode]||copy.login)[0],desc=mode==='sent'?message:(copy[mode]||copy.login)[1];
 return <main className="login-shell" dir="ltr"><section className="login-product" dir={t.dir}><div className="login-product-inner"><header className="login-brand"><ProductMark/><span>Net Expert</span></header><div className="login-proposition"><p className="login-eyebrow">ENTERPRISE ASSET OPERATIONS</p><h1>Net Expert</h1><p className="login-subtitle">Asset Operations Platform</p><p className="login-description">{ar?'مساحة موحدة لإدارة الأصول التقنية ومسؤولياتها عبر المؤسسة.':'A unified workspace for technology assets and operational accountability.'}</p></div><ul className="login-capabilities">{capabilities.map((x,i)=><li key={x.en}><span>0{i+1}</span>{ar?x.ar:x.en}</li>)}</ul><footer className="login-product-footer"><span>{ar?'مساحة عمل مؤسسية':'Enterprise workspace'}</span><span>{ar?'وصول موثوق ومحكوم':'Trusted, governed access'}</span></footer></div></section>
 <section className="login-access" dir={t.dir}><div className="login-access-inner"><div className="login-mobile-brand"><ProductMark/><span>Net Expert</span></div><div className="login-card"><div className="login-heading"><p className="login-step-label">{ar?'حساب NET EXPERT':'NET EXPERT ACCOUNT'}</p><h2>{title}</h2><p>{desc}</p></div>
 {mode==='sent'?<div className="login-sent"><span>✓</span><button className="login-submit" onClick={()=>go('login')}>{ar?'العودة لتسجيل الدخول':'Back to sign in'}</button></div>:<form onSubmit={submit} noValidate>{mode==='signup'&&<div className="login-field"><label htmlFor="full-name">{ar?'الاسم الكامل':'Full name'}</label><input id="full-name" value={fullName} onChange={e=>setFullName(e.target.value)} autoComplete="name" required autoFocus/></div>}{mode!=='newPassword'&&<div className="login-field"><label htmlFor="email">{ar?'البريد الإلكتروني':'Email address'}</label><input id="email" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" placeholder="name@company.com" required autoFocus={mode!=='signup'}/></div>}{(mode==='login'||mode==='signup'||mode==='newPassword')&&<><div className="login-field"><label htmlFor="password">{mode==='newPassword'?(ar?'كلمة المرور الجديدة':'New password'):(ar?'كلمة المرور':'Password')}</label><input id="password" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='login'?'current-password':'new-password'} required/></div>{(mode==='signup'||mode==='newPassword')&&<div className="login-field"><label htmlFor="confirm-password">{ar?'تأكيد كلمة المرور':'Confirm password'}</label><input id="confirm-password" type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password" required/></div>}</>}{mode==='login'&&<div className="login-options"><label className="login-remember"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/><span>{ar?'تذكرني':'Remember me'}</span></label><button type="button" onClick={()=>go('forgot')}>{ar?'نسيت كلمة المرور؟':'Forgot password?'}</button></div>}{error&&<div className="login-error" role="alert">{error}</div>}{message&&<div className="login-success" role="status">{message}</div>}<button className="login-submit" type="submit" disabled={loading||(mode!=='newPassword'&&!email.includes('@'))}>{loading?(ar?'جارٍ المتابعة…':'Please wait…'):mode==='login'?(ar?'تسجيل الدخول':'Sign in'):mode==='signup'?(ar?'إنشاء الحساب':'Create account'):mode==='newPassword'?(ar?'حفظ كلمة المرور':'Save password'):(ar?'إرسال الرابط':'Send link')}</button></form>}
 {mode==='login'&&<div className="login-secondary-actions"><button onClick={()=>go('signup')}>{ar?'إنشاء حساب جديد':'Create an account'}</button><button onClick={()=>go('activation')}>{ar?'إعادة إرسال رابط التفعيل':'Resend activation link'}</button></div>}{mode!=='login'&&mode!=='sent'&&<button className="login-back" onClick={()=>go('login')}>{ar?'العودة إلى تسجيل الدخول':'Back to sign in'}</button>}<p className="login-support">{ar?'الوصول محمي وفق سياسات حساب Net Expert.':'Access is protected by your Net Expert account policies.'}</p></div><footer className="login-access-footer"><span>© {new Date().getFullYear()} Net Expert</span><span>{ar?'الخصوصية والأمان':'Privacy & security'}</span></footer></div></section></main>;
}
