import {useEffect,useState} from 'react';
import {fieldsFor} from '../lib/modules';
import {bulkEdit,recordHistory,restoreVersion} from '../lib/workspace';
import SmartSelect from './SmartSelect';

export function RecordMetadata({record,ar}){return <dl className="record-metadata">{[[ar?'أنشئ بواسطة':'Created By',record.created_by_name||record.created_by],[ar?'تاريخ الإنشاء':'Created Date',record.created_at],[ar?'آخر تعديل بواسطة':'Last Modified By',record.updated_by_name||record.updated_by],[ar?'تاريخ آخر تعديل':'Last Modified Date',record.updated_at]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value|| (ar?'غير متاح للسجل التاريخي':'Not available for historical record')}</dd></div>)}</dl>}
export const quickFields=module=>fieldsFor(module).filter(f=>['status','return_status','department','assign_location','provider'].includes(f.key));
export function QuickCell({module,record,field,user,ar,onSaved}){
 const [editing,setEditing]=useState(false),[value,setValue]=useState(record[field.key]||''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>setValue(record[field.key]||''),[record,field.key]);
 if(!editing)return <button className="record-link" title={ar?'تعديل سريع':'Quick edit'} onClick={()=>setEditing(true)}>{record[field.key]||'—'} <small>✎</small></button>;
 return <div className="quick-cell"><SmartSelect list={field.list} label={ar?field.ar:field.en} scope={user.organization_id} ar={ar} value={value} onChange={setValue}/><button disabled={busy||!value} onClick={async()=>{setBusy(true);setError('');try{onSaved(await bulkEdit(module,[record],{[field.key]:value}));setEditing(false)}catch(e){setError(e.message)}finally{setBusy(false)}}}>{busy?'…':ar?'حفظ':'Save'}</button><button disabled={busy} onClick={()=>{setValue(record[field.key]||'');setEditing(false)}}>{ar?'إلغاء':'Cancel'}</button>{error&&<p role="alert" className="work-error">{error}</p>}</div>
}
export function BulkEditor({module,records,user,ar,onSaved,onClose}){
 const [patch,setPatch]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <div className="work-overlay"><section className="work-details" role="dialog" aria-modal="true" aria-label="Bulk edit"><header><h2>{ar?'تعديل جماعي':'Bulk edit'} · {records.length}</h2><button disabled={busy} onClick={onClose}>×</button></header><p>{ar?'فعّل الحقول المراد تعديلها فقط. بقية الحقول لن تتغير.':'Enable only the fields to update. All other values remain unchanged.'}</p>{quickFields(module).map(f=><div className="bulk-field" key={f.key}><label><input type="checkbox" checked={f.key in patch} onChange={e=>setPatch(p=>{const n={...p};if(e.target.checked)n[f.key]='';else delete n[f.key];return n})}/>{ar?f.ar:f.en}</label>{f.key in patch&&<SmartSelect list={f.list} label={ar?f.ar:f.en} scope={user.organization_id} ar={ar} value={patch[f.key]} onChange={v=>setPatch(p=>({...p,[f.key]:v}))}/>}</div>)}{error&&<p role="alert" className="work-error">{error}</p>}<footer><button disabled={busy} onClick={onClose}>{ar?'إلغاء':'Cancel'}</button><button className="work-primary" disabled={busy||!Object.keys(patch).length||Object.values(patch).some(v=>!v)} onClick={async()=>{setBusy(true);setError('');try{onSaved(await bulkEdit(module,records,patch));onClose()}catch(e){setError(e.message)}finally{setBusy(false)}}}>{busy?'…':ar?'تطبيق على المحدد':'Apply to selected'}</button></footer></section></div>
}
const display=value=>value===null||value===undefined||value===''?'—':typeof value==='object'?JSON.stringify(value):String(value);
export function VersionHistory({module,record,write,ar,onSaved}){
 const [history,setHistory]=useState([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{let alive=true;setLoading(true);recordHistory(record.id).then(r=>{if(alive)setHistory(r)}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false}},[record.id,record.version]);
 const fields=fieldsFor(module);
 return <section className="version-history"><h3>{ar?'سجل التدقيق والإصدارات':'Audit & version history'}</h3>{loading&&<p role="status">{ar?'جارٍ التحميل…':'Loading…'}</p>}{error&&<p className="work-error" role="alert">{error}</p>}{history.map(v=><article key={v.id}><header><strong>{ar?'إصدار':'Version'} {v.version} · {v.action}</strong>{write&&v.version<record.version&&v.action!=='delete'&&<button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{onSaved(await restoreVersion(record,v.version))}catch(e){setError(e.message)}finally{setBusy(false)}}}>{ar?'استعادة هذا الإصدار':'Restore this version'}</button>}</header><p>{v.actor_name||v.actor_id||'Historical record'} · <time dateTime={v.occurred_at}>{new Date(v.occurred_at).toLocaleString(ar?'ar-SA':'en-GB')}</time></p>{v.action==='baseline'&&<p>{ar?'نقطة بداية للسجل الموجود؛ التغييرات الأقدم غير متاحة.':'Baseline of an existing record; earlier changes are unavailable.'}</p>}<dl>{Object.entries(v.changes).map(([key,change])=>{const f=fields.find(f=>f.key===key);return <div key={key}><dt>{f?(ar?f.ar:f.en):key}</dt><dd><del>{display(change.old)}</del> → <ins>{display(change.new)}</ins></dd></div>})}</dl></article>)}<p className="work-muted">{ar?'الاستعادة تحفظ إصداراً جديداً ولا تمحو التاريخ.':'Restoring creates a new version and never erases history.'}</p></section>
}

