import {useEffect,useId,useRef,useState} from 'react';
import {supabase} from '../lib/supabase';
import {choices} from '../lib/modules';
export default function SmartSelect({list,value,onChange,ar,label,required=false,creatable=true,scope}){
 const [query,setQuery]=useState(value||''),[open,setOpen]=useState(false),[items,setItems]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[active,setActive]=useState(0);const root=useRef(),id=useId();
 useEffect(()=>setQuery(value||''),[value]);
 useEffect(()=>{let alive=true;supabase.from('workspace_choices').select('value,uses').eq('kind',list).then(({data,error})=>{if(alive){if(error)setError(error.message);else setItems(data||[])}});return()=>{alive=false}},[list,scope]);
 useEffect(()=>{const close=e=>{if(!root.current?.contains(e.target)){setOpen(false);setQuery(value||'')}};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[value]);
 const values=[...new Set([...(choices[list]||[]),...items.map(x=>x.value),...(value?[value]:[])])].sort((a,b)=>(items.find(x=>x.value===b)?.uses||0)-(items.find(x=>x.value===a)?.uses||0)||a.localeCompare(b,'ar'));
 const filtered=values.filter(x=>x.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
 const canCreate=creatable&&query.trim()&&!values.some(x=>x.toLocaleLowerCase()===query.trim().toLocaleLowerCase());
 const pick=async v=>{if(busy)return;setBusy(true);setError('');try{if(creatable){const {error}=await supabase.rpc('use_workspace_choice',{p_kind:list,p_value:v.trim()});if(error)throw error;setItems(p=>[...p.filter(x=>x.value!==v),{value:v,uses:(p.find(x=>x.value===v)?.uses||0)+1}]);}onChange(v);setQuery(v);setOpen(false)}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <div className="smart-select" ref={root}><input aria-label={label} role="combobox" aria-expanded={open} aria-controls={id} aria-autocomplete="list" aria-required={required} aria-activedescendant={open?`${id}-${active}`:undefined} value={query} disabled={busy} placeholder={ar?'ابحث أو أضف قيمة…':'Search or create…'} onFocus={()=>{setQuery('');setOpen(true);setActive(0)}} onChange={e=>{setQuery(e.target.value);setOpen(true);setActive(0)}} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);setQuery(value||'')}if(e.key==='Tab'){setOpen(false);setQuery(value||'')}if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);setActive(n=>Math.min(n+1,filtered.length+(canCreate?1:0)-1))}if(e.key==='ArrowUp'){e.preventDefault();setActive(n=>Math.max(0,n-1))}if(e.key==='Enter'&&open){e.preventDefault();if(filtered[active])pick(filtered[active]);else if(canCreate)pick(query.trim())}}}/>{open&&<div role="listbox" id={id} className="smart-options">{!required&&<button type="button" onClick={()=>{onChange('');setQuery('');setOpen(false)}}>{ar?'مسح الاختيار':'Clear selection'}</button>}{filtered.map((x,i)=><button role="option" aria-selected={value===x} id={`${id}-${i}`} className={i===active?'highlight':''} type="button" key={x} onClick={()=>pick(x)}>{x}{items.find(v=>v.value===x)?.uses>0&&<small>{ar?'مستخدم سابقاً':'Previously used'}</small>}</button>)}{canCreate&&<button role="option" aria-selected={false} id={`${id}-${filtered.length}`} type="button" onClick={()=>pick(query.trim())}>+ {ar?'إضافة':'Create'} “{query.trim()}”</button>}{!filtered.length&&!canCreate&&<p>{ar?'لا توجد نتائج':'No matches'}</p>}</div>}{error&&<small role="alert" className="work-error">{error}</small>}</div>;
}
