import { useEffect, useState } from 'react';
import { useAuth } from './AuthContext';
import { SECTIONS } from '../lib/rbac';

const ROLES=['viewer','operator','manager','company_admin'];
export default function UsersPanel({t,onClose}){
 const {users,refreshUsers,updateMember,inviteUser,deleteUser,user:me}=useAuth(),ar=t.dir==='rtl';
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(''),[error,setError]=useState(''),[invite,setInvite]=useState(false),[form,setForm]=useState({fullName:'',email:'',department:'',role:'viewer'}),[selected,setSelected]=useState(null);
 useEffect(()=>{refreshUsers().catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const run=async(id,fn)=>{setSaving(id);setError('');try{await fn()}catch(e){console.error('User management failed',{message:e.message,code:e.code});setError(e.message)}finally{setSaving('')}};
 const saveMember=(member,changes)=>run(member.id,()=>updateMember(member.id,changes));
 const submitInvite=e=>{e.preventDefault();run('invite',async()=>{await inviteUser(form);setInvite(false);setForm({fullName:'',email:'',department:'',role:'viewer'})})};
 const roleLabel=r=>({company_admin:ar?'مسؤول الشركة':'Company admin',manager:ar?'مدير':'Manager',operator:ar?'مشغّل':'Operator',viewer:ar?'مشاهد':'Viewer'})[r]||r;
 return <div className="account-dialog" dir={t.dir}><button className="account-dialog-backdrop" onClick={onClose}/><section className="account-panel tenant-users"><header><div><p>{ar?'إدارة مساحة العمل':'WORKSPACE ADMINISTRATION'}</p><h2>{ar?'المستخدمون والصلاحيات':'Users & permissions'}</h2><span>{me.organization_name}</span></div><div className="account-header-actions"><button className="ne-primary" onClick={()=>setInvite(v=>!v)}>+ {ar?'إضافة مستخدم':'Add user'}</button><button onClick={onClose}>×</button></div></header>
 {error&&<div className="login-error">{error}</div>}
 {invite&&<form className="member-invite" onSubmit={submitInvite}><input required placeholder={ar?'الاسم الكامل':'Full name'} value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/><input required type="email" placeholder="name@company.com" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder={ar?'القسم':'Department'} value={form.department} onChange={e=>setForm({...form,department:e.target.value})}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{ROLES.map(r=><option key={r} value={r}>{roleLabel(r)}</option>)}</select><button className="ne-primary" disabled={saving==='invite'}>{ar?'إرسال الدعوة':'Send invite'}</button></form>}
 <div className="account-table"><div className="account-table-head"><span>{ar?'المستخدم':'User'}</span><span>{ar?'الحالة':'Status'}</span><span>{ar?'الدور':'Role'}</span></div>{loading?<p className="account-empty">{ar?'جارٍ التحميل…':'Loading…'}</p>:users.map(u=><div key={u.id}><div className="account-row"><div><i>{(u.full_name||u.email).slice(0,2).toUpperCase()}</i><span><b>{u.full_name||u.email}</b><small>{u.email} · {u.department||'—'}</small></span></div><button className={'account-status '+u.status} onClick={()=>u.id!==me.id&&saveMember(u,{status:u.status==='active'?'suspended':'active'})}>{u.status}</button><div className="member-actions"><select value={u.role} disabled={saving===u.id||u.id===me.id} onChange={e=>saveMember(u,{role:e.target.value})}>{ROLES.map(r=><option key={r} value={r}>{roleLabel(r)}</option>)}</select><button onClick={()=>setSelected(selected===u.id?null:u.id)}>{ar?'الصلاحيات':'Access'}</button>{u.id!==me.id&&<button className="member-delete" onClick={()=>confirm(ar?'حذف المستخدم؟':'Delete this user?')&&run(u.id,()=>deleteUser(u.id))}>{ar?'حذف':'Delete'}</button>}</div></div>
 {selected===u.id&&<div className="permission-grid">{SECTIONS.map(section=>{const allowed=u.role==='company_admin'||u.permissions?.[section]===true;return <label key={section}><input type="checkbox" checked={allowed} disabled={u.role==='company_admin'||saving===u.id} onChange={e=>saveMember(u,{permissions:{...(u.permissions||{}),[section]:e.target.checked}})}/><span>{section}</span></label>})}</div>}</div>)}</div>
 <footer><p>{ar?'تُطبّق الصلاحيات على القائمة والصفحات وطلبات البيانات داخل مساحة العمل فقط.':'Access is enforced across navigation, pages, and tenant data requests.'}</p><button onClick={onClose}>{ar?'إغلاق':'Close'}</button></footer></section></div>
}
