// ─── Translations ─────────────────────────────────────────────────────────────
export const T = {
  ar: {
    dir: 'rtl',
    appName: 'خبير الشبكة',
    appSub: 'نظام إدارة الجرد التقني',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    loginBtn: 'دخول',
    wrongCreds: 'اسم المستخدم أو كلمة المرور غير صحيحة',
    addDevice: 'إضافة جهاز',
    search: 'بحث...',
    all: 'الكل',
    online: 'متصل',
    offline: 'غير متصل',
    total: 'الإجمالي',
    exportExcel: 'تصدير CSV / Excel',
    exportPDF: 'تصدير PDF',
    saveSheets: 'حفظ في Sheets',
    sheetsSaved: '✓ تم الحفظ في Google Sheets',
    sheetsError: '✗ تأكد من إعداد Google Sheets API',
    users: 'المستخدمون',
    addUser: 'إضافة مستخدم',
    role: 'الصلاحية',
    admin: 'مسؤول',
    viewer: 'مشاهد',
    settings: 'الإعدادات',
    accountSettings: 'إعدادات الحساب',
    changePassword: 'تغيير كلمة المرور',
    oldPassword: 'كلمة المرور القديمة',
    newPassword: 'كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور الجديدة',
    passwordChanged: '✓ تم تغيير كلمة المرور بنجاح',
    passwordError: '✗ كلمة المرور القديمة غير صحيحة',
    passwordMismatch: '✗ كلمات المرور الجديدة غير متطابقة',
    passwordShort: '✗ كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    sheetsPlaceholder: 'https://script.google.com/macros/s/YOUR_SCRIPT_ID/exec',
    save: 'حفظ',
    cancel: 'إلغاء',
    noResults: 'لا توجد نتائج',
    confirmDelete: 'هل تريد حذف هذا الجهاز؟',
    delete: 'حذف',
    edit: 'تعديل',
    dashboard: 'الرئيسية',
    inventory: 'الجرد',
    auditLog: 'سجل العمليات',
    auditEmpty: 'لا توجد عمليات مسجلة بعد',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    colorTheme: 'لون الواجهة',
    table: {
      name: 'اسم الجهاز', type: 'النوع', status: 'الحالة',
      serial: 'الرقم التسلسلي', location: 'الموقع', connection: 'الاتصال',
      actions: 'إجراءات', employee: 'الموظف المسؤول', empId: 'الرقم الوظيفي',
      addedBy: 'أضيف بواسطة', addedAt: 'تاريخ الإضافة', attachment: 'الملف', notes: 'ملاحظات',
    },
    modal: {
      addTitle: 'إضافة جهاز جديد', editTitle: 'تعديل الجهاز',
      name: 'اسم الجهاز', type: 'النوع', status: 'الحالة',
      serial: 'الرقم التسلسلي', location: 'الموقع', connection: 'متصل بالشبكة',
      employee: 'اسم الموظف المسؤول', empId: 'الرقم الوظيفي',
      attachment: 'إرفاق ملف (صورة أو PDF)',
      attachmentHint: 'اسحب وأفلت أو اضغط للاختيار',
      uploading: 'جاري الرفع...',
      uploadDone: '✓ تم الرفع',
      uploadError: '✗ فشل الرفع',
      viewFile: 'عرض الملف',
      save: 'حفظ', cancel: 'إلغاء',
      typeHint: 'اكتب أو اختر من القائمة',
      required: 'الاسم والرقم التسلسلي مطلوبان',
    },
    audit: {
      action: 'العملية', device: 'الجهاز', oldVal: 'القيمة القديمة',
      newVal: 'القيمة الجديدة', user: 'المستخدم', time: 'الوقت',
      added: 'إضافة', edited: 'تعديل', deleted: 'حذف', passwordChanged: 'تغيير كلمة المرور',
    },
    deviceTypes: {
      router: 'راوتر', switch: 'سويتش', ap: 'نقطة وصول', firewall: 'جدار حماية',
      server: 'خادم', nas: 'أجهزة تخزين', ups: 'وحدات الطاقة', rack: 'كبائن الشبكة',
      phone: 'هاتف IP', computer: 'كمبيوتر', accessory: 'ملحق',
    },
    statuses: { new: 'جديد', used: 'مستخدم', damaged: 'تالف' },
    locations: { warehouse: 'المستودع', main: 'المبنى الرئيسي', factory: 'المصنع' },
  },
  en: {
    dir: 'ltr',
    appName: 'Net Expert',
    appSub: 'Technical Inventory Management',
    login: 'Login',
    logout: 'Logout',
    username: 'Username',
    password: 'Password',
    loginBtn: 'Sign In',
    wrongCreds: 'Invalid username or password',
    addDevice: 'Add Device',
    search: 'Search...',
    all: 'All',
    online: 'Online',
    offline: 'Offline',
    total: 'Total',
    exportExcel: 'Export CSV / Excel',
    exportPDF: 'Export PDF',
    saveSheets: 'Save to Sheets',
    sheetsSaved: '✓ Saved to Google Sheets',
    sheetsError: '✗ Check Google Sheets API config',
    users: 'Users',
    addUser: 'Add User',
    role: 'Role',
    admin: 'Admin',
    viewer: 'Viewer',
    settings: 'Settings',
    accountSettings: 'Account Settings',
    changePassword: 'Change Password',
    oldPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    passwordChanged: '✓ Password changed successfully',
    passwordError: '✗ Current password is incorrect',
    passwordMismatch: '✗ New passwords do not match',
    passwordShort: '✗ Password must be at least 6 characters',
    sheetsPlaceholder: 'https://script.google.com/macros/s/YOUR_SCRIPT_ID/exec',
    save: 'Save',
    cancel: 'Cancel',
    noResults: 'No results found',
    confirmDelete: 'Delete this device?',
    delete: 'Delete',
    edit: 'Edit',
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    auditLog: 'Audit Log',
    auditEmpty: 'No operations recorded yet',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    colorTheme: 'Color Theme',
    table: {
      name: 'Device Name', type: 'Type', status: 'Status',
      serial: 'Serial Number', location: 'Location', connection: 'Connection',
      actions: 'Actions', employee: 'Responsible Employee', empId: 'Employee ID',
      addedBy: 'Added By', addedAt: 'Date Added', attachment: 'File', notes: 'Notes',
    },
    modal: {
      addTitle: 'Add New Device', editTitle: 'Edit Device',
      name: 'Device Name', type: 'Type', status: 'Status',
      serial: 'Serial Number', location: 'Location', connection: 'Connected to Network',
      employee: 'Responsible Employee Name', empId: 'Employee ID',
      attachment: 'Attach File (Image or PDF)',
      attachmentHint: 'Drag & drop or click to choose',
      uploading: 'Uploading...',
      uploadDone: '✓ Uploaded',
      uploadError: '✗ Upload failed',
      viewFile: 'View File',
      save: 'Save', cancel: 'Cancel',
      typeHint: 'Type or select from list',
      required: 'Name and Serial Number are required',
    },
    audit: {
      action: 'Action', device: 'Device', oldVal: 'Old Value',
      newVal: 'New Value', user: 'User', time: 'Time',
      added: 'Added', edited: 'Edited', deleted: 'Deleted', passwordChanged: 'Password Changed',
    },
    deviceTypes: {
      router: 'Router', switch: 'Switch', ap: 'Access Point', firewall: 'Firewall',
      server: 'Server', nas: 'NAS Storage', ups: 'UPS', rack: 'Rack Cabinet',
      phone: 'IP Phone', computer: 'Computer', accessory: 'Accessory',
    },
    statuses: { new: 'New', used: 'In Use', damaged: 'Damaged' },
    locations: { warehouse: 'Warehouse', main: 'Main Building', factory: 'Factory' },
  },
};

// ─── Initial Data ──────────────────────────────────────────────────────────────
export const INITIAL_DEVICES = [];

// Authentication and membership records are loaded exclusively from Supabase.
export const INITIAL_USERS = [];

export const TYPE_COLORS = {
  router:   { bg:'bg-cyan-500/15',    text:'text-cyan-400',    border:'border-cyan-500/30'    },
  switch:   { bg:'bg-blue-500/15',    text:'text-blue-400',    border:'border-blue-500/30'    },
  ap:       { bg:'bg-teal-500/15',    text:'text-teal-400',    border:'border-teal-500/30'    },
  firewall: { bg:'bg-red-500/15',     text:'text-red-400',     border:'border-red-500/30'     },
  server:   { bg:'bg-violet-500/15',  text:'text-violet-400',  border:'border-violet-500/30'  },
  nas:      { bg:'bg-purple-500/15',  text:'text-purple-400',  border:'border-purple-500/30'  },
  ups:      { bg:'bg-amber-500/15',   text:'text-amber-400',   border:'border-amber-500/30'   },
  rack:     { bg:'bg-stone-500/15',   text:'text-stone-400',   border:'border-stone-500/30'   },
  phone:    { bg:'bg-emerald-500/15', text:'text-emerald-400', border:'border-emerald-500/30' },
  computer: { bg:'bg-sky-500/15',     text:'text-sky-400',     border:'border-sky-500/30'     },
  accessory:{ bg:'bg-pink-500/15',    text:'text-pink-400',    border:'border-pink-500/30'    },
};

export const LOC_COLORS = {
  warehouse: 'bg-amber-500/10 text-amber-400 border-amber-500/25',
  main:      'bg-cyan-500/10 text-cyan-400 border-cyan-500/25',
  factory:   'bg-violet-500/10 text-violet-400 border-violet-500/25',
};
