export const choices = {
 department: ['Sales','Finance','HR','IT','Operations','Production','Management'],
 assign_location: ['Riyadh','Jeddah','Dammam','Factory','Head Office'],
 provider: ['STC','Mobily','Zain'], sim_package: ['20GB','50GB','100GB','Unlimited'],
 hardware: ['Laptop','Desktop PC','Workstation','Monitor','Smartphone','Tablet','Printer','Scanner','SIM','Server','Router','Switch','Firewall','Access Point','UPS','CCTV Camera','Barcode Scanner','Handheld Device','Storage Device','Other'],
 brand: ['HP','Dell','Lenovo','Acer','Asus','Apple','Samsung','Huawei','Cisco','Fortinet','Mikrotik','Zebra','Honeywell','STC','Mobily','Zain','Other'],
 supplier: [], priority:['Low','Medium','High','Urgent'],
 sim_status:['Active','Suspended','Returned','Lost','Damaged'],
 asset_status:['In Use','Available','Under Maintenance','Damaged','Lost','Retired','Returned'],
 purchase_status:['Draft','Pending Approval','Approved','Ordered','Received','Cancelled']
};
const f=(key,en,ar,type='text',required=false,list)=>({key,en,ar,type,required,list});
const employee=[f('employee_id','Employee ID','الرقم الوظيفي','text',true),f('employee_name','Employee Name','اسم الموظف','text',true),f('email_address','Email Address','البريد الإلكتروني','email'),f('department','Department','القسم','select',true,'department'),f('assign_location','Assign Location','موقع العهدة','select',true,'assign_location')];
const hardware=[f('hardware','Type Of Hardware','نوع العتاد','select',true,'hardware'),f('brand','Brand / Manufacturer','العلامة / الشركة المصنعة','select',true,'brand'),f('model','Model Name','الموديل')];
const notes=[f('notes','Notes','ملاحظات','textarea')];
export const modules={
 sim:{en:'SIM Custody',ar:'عهد شرائح SIM',groups:[['Employee Information','بيانات الموظف',employee],['SIM Information','بيانات الشريحة',[f('mobile_number','Mobile Number','رقم الجوال','tel',true),f('sim_number','SIM Number','رقم الشريحة','text',true),f('account_number','Account Number','رقم الحساب'),f('provider','Provider','المزود','select',true,'provider'),f('sim_package','SIM Package','الباقة','select',false,'sim_package')]],['Custody Information','بيانات العهدة',[f('date_issued','Date Issued','تاريخ التسليم','date',true),f('date_returned','Date Returned','تاريخ الإرجاع','date'),f('status','Status','الحالة','select',true,'sim_status'),...notes]]],columns:['employee_id','employee_name','date_issued','email_address','department','assign_location','provider','sim_number','mobile_number','sim_package','status'],date:'date_issued',charts:[['provider','SIMs by Provider','الشرائح حسب المزود'],['department','SIMs by Department','الشرائح حسب القسم'],['date_issued','Monthly Assignments','التسليمات الشهرية','month']]},
 assets:{en:'IT Assets',ar:'الأصول التقنية',groups:[['Employee Information','بيانات الموظف',employee],['Asset Information','بيانات الأصل',[...hardware,f('serial_number','Serial Number','الرقم التسلسلي','text',true),f('asset_tag','Asset Tag','رمز الأصل')]],['Warranty','الضمان',[f('warranty_start','Warranty Start Date','بداية الضمان','date'),f('warranty_end','Warranty End Date','نهاية الضمان','date')]],['Status','الحالة',[f('status','Asset Status','حالة الأصل','select',true,'asset_status')]],['Additional Information','بيانات إضافية',notes]],columns:['asset_tag','hardware','brand','model','serial_number','employee_name','department','assign_location','status','warranty_end'],date:'created_at',charts:[['hardware','Assets by Type','الأصول حسب النوع'],['brand','Assets by Brand','الأصول حسب العلامة'],['department','Assets by Department','الأصول حسب القسم'],['warranty_end','Warranty Expiration Trend','انتهاء الضمان شهرياً','month']]},
 purchasing:{en:'Purchasing',ar:'المشتريات',groups:[['Request Information','بيانات الطلب',[f('request_number','Request Number','رقم الطلب','text',true),f('request_date','Request Date','تاريخ الطلب','date',true),f('requested_by','Requested By','مقدم الطلب','text',true),f('department','Department','القسم','select',true,'department')]],['Asset Information','بيانات الأصل',hardware],['Purchase Information','بيانات الشراء',[f('quantity','Quantity','الكمية','number',true),f('estimated_cost','Estimated Cost (total, SAR)','التكلفة التقديرية الإجمالية (ر.س)','number'),f('supplier','Supplier','المورد','select',false,'supplier'),f('priority','Priority','الأولوية','select',true,'priority'),f('status','Purchase Status','حالة الطلب','select',true,'purchase_status')]],['Delivery Information','بيانات التسليم',[f('po_number','PO Number','رقم أمر الشراء'),f('invoice_number','Invoice Number','رقم الفاتورة'),f('expected_delivery','Expected Delivery Date','التسليم المتوقع','date'),f('received_date','Received Date','تاريخ الاستلام','date')]],['Additional Information','بيانات إضافية',[f('justification','Justification','مبررات الطلب','textarea'),...notes]]],columns:['request_number','request_date','requested_by','department','hardware','brand','quantity','estimated_cost','supplier','priority','status'],date:'request_date',charts:[['department','Purchases by Department','المشتريات حسب القسم'],['hardware','Purchases by Category','المشتريات حسب الفئة'],['request_date','Monthly Spending (estimated SAR)','الإنفاق الشهري التقديري (ر.س)','spend']]}
};
export const fieldsFor=key=>modules[key].groups.flatMap(g=>g[2]);
export function validateRecord(module,data){
 for(const f of fieldsFor(module)){if(f.required&&!String(data[f.key]??'').trim())return `${f.en} is required`;if(f.type==='email'&&data[f.key]&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data[f.key]))return 'Invalid email address';}
 if(data.date_returned&&data.date_returned<data.date_issued)return 'Return date must follow issue date';
 if(data.warranty_end&&data.warranty_start&&data.warranty_end<data.warranty_start)return 'Warranty end must follow start';
 if(module==='purchasing'&&(!Number.isInteger(Number(data.quantity))||Number(data.quantity)<1))return 'Quantity must be a positive whole number';
 if(data.estimated_cost&&(!Number.isFinite(Number(data.estimated_cost))||Number(data.estimated_cost)<0))return 'Cost must be zero or greater';
 return '';
}
export function metrics(module,rows){const count=s=>rows.filter(r=>r.status===s).length;return module==='sim'?[['Total SIMs','إجمالي الشرائح',rows.length],...['Active','Suspended','Returned','Lost'].map((s,i)=>[`${s} SIMs`,['نشطة','موقوفة','مُعادة','مفقودة'][i],count(s)])]:module==='assets'?[['Total Assets','إجمالي الأصول',rows.length],['Assigned Assets','أصول مستخدمة',count('In Use')],['Available Assets','أصول متاحة',count('Available')],['Maintenance Assets','تحت الصيانة',count('Under Maintenance')],['Lost Assets','أصول مفقودة',count('Lost')],['Expired Warranty','ضمان منتهٍ',rows.filter(r=>r.warranty_end&&r.warranty_end<new Date().toISOString().slice(0,10)).length]]:[['Total Requests','إجمالي الطلبات',rows.length],...['Pending Approval','Approved','Ordered','Received'].map((s,i)=>[s,['بانتظار الموافقة','معتمدة','تم الطلب','مستلمة'][i],count(s)]),['Total Purchase Cost (estimated SAR)','التكلفة الإجمالية التقديرية (ر.س)',rows.filter(r=>r.status!=='Cancelled').reduce((n,r)=>n+Number(r.estimated_cost||0),0)]];}
