import {useEffect,useState} from 'react';
import Head from 'next/head';
import {useRouter} from 'next/router';
import {useAuth} from '../components/AuthContext';
import LoginPage from '../components/LoginPage';
import UsersPanel from '../components/UsersPanel';
import WorkspaceModule from '../components/WorkspaceModule';
import ExportCenter from '../components/ExportCenter';
import {T} from '../lib/data';
import {canAccessPage} from '../lib/rbac';
const navigation=[['sim','SIM Custody','عهد شرائح SIM'],['assets','IT Assets','الأصول التقنية'],['purchasing','Purchasing','المشتريات'],['reports','Reports','التقارير'],['exports','Export Center','مركز التصدير'],['administration','Administration','الإدارة']];
export default function NetExpert(){
 const {user,ready,recoveryMode,logout,logoutAll}=useAuth(),router=useRouter();const [lang,setLang]=useState('en'),[menu,setMenu]=useState(false),[users,setUsers]=useState(false),[error,setError]=useState('');const ar=lang==='ar',t=T[lang],page=typeof router.query.module==='string'?router.query.module:'sim';
 useEffect(()=>{const stored=localStorage.getItem('ne_language');if(stored==='ar')setLang(stored)},[]);
 const allowed=user?navigation.filter(([key])=>canAccessPage(user,key)):[];const accessible=allowed.some(([key])=>key===page);
 const go=key=>router.push({pathname:'/',query:{module:key}},undefined,{shallow:true});
 const signout=async all=>{setError('');try{await(all?logoutAll():logout())}catch(e){setError(e.message)}};
 if(!ready)return <div className="work-empty" role="status">Loading workspace…</div>;
 if(!user||recoveryMode)return <LoginPage t={t}/>;
 return <div className="workspace-app" dir={ar?'rtl':'ltr'}><Head><title>Net Expert — IT Asset Management</title></Head><aside className="workspace-sidebar"><a href="/" className="workspace-brand"><b>NE</b><span>Net Expert<small>{user.organization_name}</small></span></a><p>{ar?'مساحة العمل':'WORKSPACE'}</p><nav aria-label={ar?'التنقل':'Workspace navigation'}>{allowed.map(([key,en,arabic],i)=><button key={key} aria-current={page===key?'page':undefined} className={page===key?'active':''} onClick={()=>go(key)}><span className="nav-mark">{String(i+1).padStart(2,'0')}</span>{ar?arabic:en}</button>)}</nav><footer><span>{ar?'إدارة تقنية أبسط':'Everyday IT, simplified.'}</span><small>Net Expert</small></footer></aside><div className="workspace-main"><header className="workspace-top"><span>{ar?'مساحة العمل':'Workspace'} / <b>{navigation.find(n=>n[0]===page)?.[ar?2:1]||'—'}</b></span><button onClick={()=>{const next=ar?'en':'ar';setLang(next);localStorage.setItem('ne_language',next)}}>{ar?'English':'العربية'}</button><button onClick={()=>setMenu(!menu)} aria-expanded={menu}>{user.name||user.email} ▾</button>{menu&&<div className="workspace-account"><strong>{user.name}</strong><small>{user.email}</small><button onClick={()=>signout(false)}>{ar?'تسجيل الخروج':'Sign out'}</button><button onClick={()=>signout(true)}>{ar?'إنهاء جميع الجلسات':'Sign out all sessions'}</button></div>}</header>{error&&<p role="alert" className="work-error">{error}</p>}<main>{!accessible?<div className="work-page"><h1>{ar?'الوصول غير متاح':'Access unavailable'}</h1><p>{ar?'هذا القسم غير متاح لحسابك.':'This section is unavailable to your account.'}</p>{allowed[0]&&<button onClick={()=>go(allowed[0][0])}>{ar?'فتح مساحة العمل':'Open workspace'}</button>}</div>:['sim','assets','purchasing'].includes(page)?<WorkspaceModule key={`${user.organization_id}-${page}`} module={page} user={user} ar={ar}/>:page==='exports'||page==='reports'?<ExportCenter key={page} t={t} reports={page==='reports'}/>:<div className="work-page"><header className="work-heading"><div><small>{user.organization_name}</small><h1>{ar?'الإدارة':'Administration'}</h1><p>{ar?'إدارة أعضاء الشركة وصلاحيات الوصول.':'Manage company members and access permissions.'}</p></div></header><section className="work-admin"><h2>{ar?'المستخدمون والصلاحيات':'Users & permissions'}</h2><p>{ar?'امنح الوصول للوحدات الست حسب مسؤوليات الموظف.':'Grant module access according to each employee’s responsibilities.'}</p><button className="work-primary" onClick={()=>setUsers(true)}>{ar?'إدارة المستخدمين':'Manage users'}</button></section></div>}</main></div>{users&&<UsersPanel t={t} onClose={()=>setUsers(false)}/>}</div>
}
