import { useCallback, useEffect, useMemo, useState } from 'react';
import Head from 'next/head';
import { useAuth } from '../components/AuthContext';
import LoginPage from '../components/LoginPage';
import DeviceModal from '../components/DeviceModal';
import UsersPanel from '../components/UsersPanel';
import SettingsPanel from '../components/SettingsPanel';
import AuditLogPanel from '../components/AuditLogPanel';
import ExportCenter from '../components/ExportCenter';
import { T } from '../lib/data';
import { getDevices, addDevice, updateDevice, deleteDevice, getAuditLog, addAuditEntry } from '../lib/db';
import { exportExcel } from '../lib/export';
import { canAccessPage } from '../lib/rbac';

const labels={
 ar:{workspace:'مساحة العمل',assets:'عهد شرائح SIM',operations:'العمليات',procurement:'المشتريات',contracts:'العقود',insights:'التقارير',admin:'الإدارة',search:'ابحث باسم الموظف أو رقم الشريحة أو الجوال',create:'إضافة عهدة SIM',workQueue:'قائمة العمل',workHint:'الأعمال التي تتطلب تدخلك مرتبة حسب الأولوية',priority:'الأولوية',work:'العمل',related:'السجل المرتبط',owner:'المسؤول',due:'الاستحقاق',critical:'حرج',high:'مرتفع',medium:'متوسط',review:'مراجعة',registry:'سجل عهد شرائح SIM',records:'سجل',newAsset:'عهدة SIM جديدة',view:'العرض',activeView:'العهد النشطة',filter:'تصفية',columns:'الأعمدة',selected:'محدد',assign:'تعيين',move:'نقل',change:'تغيير الحالة',export:'تصدير',details:'تفاصيل عهدة SIM',identity:'بيانات الشريحة',responsibility:'بيانات الموظف',activity:'بيانات العهدة',full:'فتح السجل الكامل',edit:'تعديل',remove:'حذف',noResults:'لا توجد عهد SIM تطابق العرض الحالي',clear:'مسح التصفية'},
 en:{workspace:'Workspace',assets:'SIM Assignments',operations:'Operations',procurement:'Procurement',contracts:'Contracts',insights:'Insights',admin:'Administration',search:'Search employee, SIM or mobile number',create:'Add SIM assignment',workQueue:'Work queue',workHint:'Items requiring your attention, ordered by priority',priority:'Priority',work:'Work item',related:'Related record',owner:'Owner',due:'Due',critical:'Critical',high:'High',medium:'Medium',review:'Review',registry:'SIM custody register',records:'records',newAsset:'New SIM assignment',view:'View',activeView:'Active assignments',filter:'Filter',columns:'Columns',selected:'selected',assign:'Assign',move:'Move',change:'Change status',export:'Export',details:'SIM assignment details',identity:'SIM details',responsibility:'Employee details',activity:'Custody details',full:'Open full record',edit:'Edit',remove:'Delete',noResults:'No SIM assignments match the current view',clear:'Clear filters'}
};

const Icons=({name})=>{const p={workspace:<><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></>,assets:<><path d="M4 7.5 12 3l8 4.5v9L12 21l-8-4.5z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></>,operations:<><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></>,procurement:<><path d="M3 5h2l2 11h11l2-8H6"/><circle cx="9" cy="20" r="1"/><circle cx="17" cy="20" r="1"/></>,contracts:<><path d="M6 3h9l4 4v14H6z"/><path d="M14 3v5h5M9 12h7M9 16h7"/></>,insights:<path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/>,admin:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,plus:<path d="M12 5v14M5 12h14"/>,bell:<><path d="M18 9a6 6 0 0 0-12 0c0 6-3 6-3 8h18c0-2-3-2-3-8"/><path d="M10 21h4"/></>,filter:<path d="M4 5h16l-6 7v6l-4 2v-8z"/>,columns:<><rect x="3" y="4" width="18" height="16"/><path d="M9 4v16M15 4v16"/></>,refresh:<><path d="M20 6v5h-5"/><path d="M18 16a8 8 0 1 1 1-7"/></>,more:<><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>,close:<path d="m6 6 12 12M18 6 6 18"/>};return <svg viewBox="0 0 24 24" aria-hidden="true">{p[name]}</svg>};

const jobs=[{p:'critical',ar:'مراجعة شرائح موقوفة ما زالت بعهد الموظفين',en:'Review suspended SIMs still assigned to employees',r:'SIM custody register',o:'Telecom Operations',d:'متأخر يومين'},{p:'high',ar:'متابعة عهد SIM المفقودة',en:'Follow up lost SIM assignments',r:'Incident review',o:'IT Operations',d:'اليوم'},{p:'medium',ar:'استكمال بيانات الأقسام للعهد النشطة',en:'Complete department data for active assignments',r:'Custody reconciliation',o:'Asset Control',d:'12 Sep'}];

export default function NetExpert(){
 const {user,ready,recoveryMode,logout,logoutAll}=useAuth(); const [lang,setLang]=useState('ar'),[page,setPage]=useState('workspace'),[devices,setDevices]=useState([]),[audit,setAudit]=useState([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[selected,setSelected]=useState([]),[inspect,setInspect]=useState(null),[modal,setModal]=useState(false),[editing,setEditing]=useState(null),[usersOpen,setUsersOpen]=useState(false),[auditOpen,setAuditOpen]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[accountOpen,setAccountOpen]=useState(false);
 const c=labels[lang],t=T[lang],rtl=lang==='ar',admin=user?.role==='company_admin';
 const load=useCallback(async()=>{setLoading(true);const[d,a]=await Promise.all([getDevices(),getAuditLog()]);setDevices(d||[]);setAudit(a||[]);setLoading(false)},[]);
 useEffect(()=>{if(user)load()},[user,load]);
 useEffect(()=>{if(user&&user.role!=='company_admin'){const map={workspace:'dashboard',assets:'assets',operations:'operations',procurement:'procurement',contracts:'contracts',insights:'reports',exports:'reports'};if(!canAccessPage(user,map[page]||page)){const fallback=Object.keys(map).find(key=>canAccessPage(user,map[key]));setPage(fallback||'workspace')}}},[user,page]);
 const rows=useMemo(()=>devices.filter(d=>{const q=search.toLowerCase();return !q||[d.employee_id,d.employee_name,d.email_address,d.department,d.assign_location,d.sim_number,d.mobile_number,d.provider,d.sim_package,d.status].some(v=>String(v||'').toLowerCase().includes(q))}),[devices,search]);
 const save=async form=>{const old=editing,result=old?await updateDevice(form):await addDevice(form);setDevices(p=>old?p.map(x=>x.id===result.id?result:x):[result,...p]);const e={time:new Date().toISOString(),action:old?'edited':'added',deviceName:result.employee_name,deviceId:String(result.id),oldVal:old?.sim_number||'',newVal:result.sim_number,userName:user.name||user.username,userEmail:user.email||''};const saved=await addAuditEntry(e);setAudit(p=>[...p,saved]);setInspect(result);setEditing(null)};
 const remove=async d=>{if(!confirm(t.confirmDelete))return;await deleteDevice(d.id);setDevices(p=>p.filter(x=>x.id!==d.id));setInspect(null)};
 if(!ready)return null;if(!user||recoveryMode)return <LoginPage t={t}/>;
 c.exports=rtl?'مركز التصدير':'Export Center';
 const sectionFor={workspace:'dashboard',assets:'assets',operations:'operations',procurement:'procurement',contracts:'contracts',insights:'reports',exports:'reports'};
 const nav=['workspace','assets','operations','procurement','contracts','insights','exports'].filter(item=>canAccessPage(user,sectionFor[item]));
 return <div className="ne-app" dir={rtl?'rtl':'ltr'}><Head><title>Net Expert — SIM Custody Operations</title></Head>
  <aside className="ne-sidebar"><div className="ne-org"><b>NE</b><span><strong>Net Expert</strong><small>SIM custody workspace</small></span></div><nav>{nav.map(n=><button key={n} className={page===n?'active':''} onClick={()=>setPage(n)}><Icons name={n}/><span>{c[n]}</span>{n==='operations'&&<em>3</em>}</button>)}{admin&&<button className={page==='admin'?'active':''} onClick={()=>setPage('admin')}><Icons name="admin"/><span>{c.admin}</span></button>}</nav><div className="ne-saved"><p>{rtl?'العروض المحفوظة':'Saved views'}</p><button onClick={()=>{setPage('assets');setSearch('STC')}}>{rtl?'شرائح STC':'STC assignments'}</button><button onClick={()=>{setPage('assets');setSearch('Suspended')}}>{rtl?'العهد الموقوفة':'Suspended assignments'}</button></div><button className="ne-profile" onClick={()=>setAccountOpen(true)}><i>{(user.name||user.username).slice(0,2).toUpperCase()}</i><span><strong>{user.name||user.username}</strong><small>{admin?'Administrator':'Viewer'}</small></span><Icons name="more"/></button></aside>
  <section className="ne-main"><header className="ne-top"><div className="ne-crumb">Net Expert <span>/</span> <b>{c[page]}</b></div><label className="ne-search"><Icons name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} onFocus={()=>setPage('assets')} placeholder={c.search}/></label><button className="ne-primary" onClick={()=>{setEditing(null);setModal(true)}}><Icons name="plus"/>{c.create}</button><button className="ne-user-trigger" onClick={()=>setAccountOpen(v=>!v)}><i>{(user.name||user.email||'U').slice(0,2).toUpperCase()}</i><span>{user.name||user.email}</span>⌄</button>{accountOpen&&<div className="ne-user-menu"><header><b>{user.name||user.email}</b><span>{user.email}</span><small>{user.role==='admin'?(rtl?'مسؤول':'Administrator'):(rtl?'مشاهد':'Viewer')}</small></header><div className="ne-session-state"><i/><span><b>{rtl?'الجلسة الحالية':'Current session'}</b><small>{rtl?'نشطة على هذا الجهاز':'Active on this device'}</small></span></div><button onClick={()=>setLang(x=>x==='ar'?'en':'ar')}>{rtl?'Switch to English':'التبديل إلى العربية'}</button>{admin&&<button onClick={()=>{setSettingsOpen(true);setAccountOpen(false)}}>{rtl?'إعدادات المؤسسة':'Organization settings'}</button>}<button onClick={logoutAll}>{rtl?'تسجيل الخروج من جميع الجلسات':'Sign out of all sessions'}</button><button className="signout" onClick={logout}>{rtl?'تسجيل الخروج':'Sign out'}</button></div>}</header>
   <main>{page==='workspace'?<Workspace c={c} lang={lang} devices={devices} audit={audit} openAssets={()=>setPage('assets')} openAudit={()=>setAuditOpen(true)}/>:page==='assets'?<Registry c={c} t={t} rtl={rtl} rows={rows} loading={loading} selected={selected} setSelected={setSelected} inspect={inspect} setInspect={setInspect} admin={admin} refresh={load} add={()=>{setEditing(null);setModal(true)}} edit={d=>{setEditing(d);setModal(true)}} remove={remove}/>:page==='exports'?<ExportCenter t={t}/>:page==='admin'?<Admin c={c} users={()=>setUsersOpen(true)} settings={()=>setSettingsOpen(true)} audit={()=>setAuditOpen(true)}/>:<Module c={c} lang={lang} title={c[page]}/>}</main>
  </section>
  {modal&&<DeviceModal t={t} device={editing} onSave={save} onClose={()=>{setModal(false);setEditing(null)}}/>}
  {usersOpen&&<UsersPanel t={t} onClose={()=>setUsersOpen(false)}/>}
  {auditOpen&&<AuditLogPanel t={t} log={audit} onClose={()=>setAuditOpen(false)}/>}
  {settingsOpen&&<SettingsPanel t={t} onClose={()=>setSettingsOpen(false)}/>}
 </div>
}

function Workspace({c,lang,devices,audit,openAssets,openAudit}){const suspended=devices.filter(d=>d.status==='Suspended').length,lost=devices.filter(d=>d.status==='Lost').length,returned=devices.filter(d=>d.status==='Returned').length;return <div className="ne-page"><PageHead title={c.workspace} text={lang==='ar'?'عهد شرائح SIM والتغييرات التي تحتاج متابعة.':'SIM assignments and changes requiring your attention.'}/><div className="ne-brief"><b>{lang==='ar'?'ملخص العهد':'Custody brief'}</b><p>{lang==='ar'?`يوجد ${suspended+lost} سجل عهدة يحتاج متابعة. راجع الحالات الموقوفة والمفقودة.`:`${suspended+lost} assignments require attention. Review suspended and lost SIMs.`}</p><button onClick={openAssets}>{lang==='ar'?'مراجعة عهد SIM':'Review SIM assignments'} →</button></div><div className="ne-grid"><section className="ne-panel"><PanelHead title={c.workQueue} text={c.workHint}/><JobTable c={c} lang={lang}/></section><aside className="ne-context"><h2>{lang==='ar'?'سياقي':'My context'}</h2><Context label={lang==='ar'?'عهد نشطة':'Active assignments'} value={devices.filter(d=>['Active','Excellent'].includes(d.status)).length}/><Context label={lang==='ar'?'عهد موقوفة':'Suspended'} value={suspended}/><Context label={lang==='ar'?'شرائح مفقودة':'Lost'} value={lost} danger/><h3>{lang==='ar'?'آخر التغييرات':'Recent changes'}</h3>{[...audit].reverse().slice(0,4).map((a,i)=><button key={i} onClick={openAudit}><b>{a.deviceName||'SIM record'}</b><small>{a.userName}</small></button>)}</aside></div><section className="ne-panel ne-condition-panel"><PanelHead title={lang==='ar'?'حالة سجل العهد':'Custody register condition'} text={lang==='ar'?'السجلات التي تحتاج قرارًا تشغيلياً.':'Assignments requiring an operational decision.'}/><div className="ne-conditions"><Condition value={suspended} label={lang==='ar'?'شرائح موقوفة':'Suspended SIMs'} note={lang==='ar'?'تحتاج مراجعة سبب الإيقاف':'Review suspension reason'}/><Condition value={lost} label={lang==='ar'?'شرائح مفقودة':'Lost SIMs'} note={lang==='ar'?'تحتاج إيقافاً ومتابعة':'Require blocking and follow-up'}/><Condition value={returned} label={lang==='ar'?'عهد مُعادة':'Returned assignments'} note={lang==='ar'?'جاهزة للمطابقة أو إعادة التعيين':'Ready for reconciliation'}/></div></section></div>}
const PageHead=({title,text,action})=><div className="ne-heading"><div><h1>{title}</h1><p>{text}</p></div>{action}</div>;
const PanelHead=({title,text})=><div className="ne-panel-head"><div><h2>{title}</h2><p>{text}</p></div></div>;
function JobTable({c,lang}){return <div className="ne-table-scroll"><table className="ne-table"><thead><tr><th>{c.priority}</th><th>{c.work}</th><th>{c.related}</th><th>{c.owner}</th><th>{c.due}</th><th/></tr></thead><tbody>{jobs.map((j,i)=><tr key={i}><td><span className={'ne-priority '+j.p}>{c[j.p]}</span></td><td><b>{j[lang]}</b></td><td>{j.r}</td><td>{j.o}</td><td>{j.d}</td><td><button>{c.review}</button></td></tr>)}</tbody></table></div>}
const Context=({label,value,danger})=><div className="ne-context-row"><span>{label}</span><b className={danger?'danger':''}>{value}</b></div>;
const Condition=({value,label,note})=><button className="ne-condition"><b>{value}</b><span>{label}<small>{note}</small></span><strong>→</strong></button>;

function Registry({c,t,rtl,rows,loading,selected,setSelected,inspect,setInspect,admin,refresh,add,edit,remove}){const all=rows.length>0&&rows.every(d=>selected.includes(d.id)),toggle=id=>setSelected(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]),date=v=>v?new Date(`${v}T00:00:00`).toLocaleDateString(rtl?'ar-SA':'en-GB'):'—';return <div className="ne-registry"><PageHead title={c.registry} text={`${rows.length} ${c.records}`} action={admin&&<button className="ne-primary" onClick={add}><Icons name="plus"/>{c.newAsset}</button>}/><div className={'ne-viewbar '+(selected.length?'selection':'')}>{selected.length?<><b>{selected.length} {c.selected}</b><button>{c.change}</button><button onClick={()=>exportExcel(rows,t)}>{c.export}</button><i/><button onClick={()=>setSelected([])}><Icons name="close"/></button></>:<><button className="ne-view"><small>{c.view}</small>{c.activeView}⌄</button><i/><button><Icons name="filter"/>{c.filter}</button><button><Icons name="columns"/>{c.columns}</button><button onClick={refresh}><Icons name="refresh"/></button></>}</div><div className="ne-registry-body"><div className="ne-table-scroll ne-assets"><table className="ne-table sim-table"><thead><tr><th><input type="checkbox" checked={all} onChange={()=>setSelected(all?[]:rows.map(d=>d.id))}/></th><th>Employee ID</th><th>Employee Name</th><th>Date Issued</th><th>Email Address</th><th>Department</th><th>Assign Location</th><th>Provider</th><th>SIM Number</th><th>Mobile Number</th><th>SIM Package</th><th>Status</th></tr></thead><tbody>{loading?<tr><td colSpan="12" className="ne-empty">{rtl?'جاري تحميل سجل العهد…':'Loading custody register…'}</td></tr>:rows.length===0?<tr><td colSpan="12" className="ne-empty"><b>{c.noResults}</b></td></tr>:rows.map(d=><tr key={d.id} className={inspect?.id===d.id?'current':''} onClick={()=>setInspect(d)}><td onClick={e=>e.stopPropagation()}><input type="checkbox" checked={selected.includes(d.id)} onChange={()=>toggle(d.id)}/></td><td className="mono">{d.employee_id}</td><td><b>{d.employee_name}</b></td><td>{date(d.date_issued)}</td><td>{d.email_address||'—'}</td><td><span className="sim-badge department">{d.department}</span></td><td>{d.assign_location||'—'}</td><td><span className="sim-badge provider">{d.provider}</span></td><td className="mono">{d.sim_number}</td><td className="mono">{d.mobile_number}</td><td>{d.sim_package||'—'}</td><td><span className={'sim-badge status '+String(d.status||'').toLowerCase()}>{d.status}</span></td></tr>)}</tbody></table></div>{inspect&&<Inspector d={inspect} c={c} rtl={rtl} admin={admin} close={()=>setInspect(null)} edit={()=>edit(inspect)} remove={()=>remove(inspect)}/>}</div></div>}
function Inspector({d,c,rtl,admin,close,edit,remove}){const date=v=>v?new Date(`${v}T00:00:00`).toLocaleDateString(rtl?'ar-SA':'en-GB'):'—';return <aside className="ne-inspector"><header><div><small>{c.details}</small><h2>{d.employee_name}</h2><p>{d.mobile_number} · {d.provider}</p></div><button onClick={close}><Icons name="close"/></button></header><div className="ne-inspector-actions">{admin&&<button className="ne-primary" onClick={edit}>{c.edit}</button>}<button><Icons name="more"/></button></div>{['Lost','Suspended','Damaged'].includes(d.status)&&<div className="ne-alert"><b>{rtl?'تحتاج متابعة':'Follow-up required'}</b><p>{rtl?'حالة العهدة تتطلب إجراءً من فريق العمليات.':'This assignment status requires an operations action.'}</p></div>}<Properties title={c.responsibility} rows={[["Employee ID",d.employee_id],["Employee Name",d.employee_name],["Email Address",d.email_address||'—'],["Department",d.department],["Assign Location",d.assign_location||'—']]}/><Properties title={c.identity} rows={[["Provider",d.provider],["SIM Number",d.sim_number],["Mobile Number",d.mobile_number],["Account Number",d.account_number||'—'],["SIM Package",d.sim_package||'—']]}/><Properties title={c.activity} rows={[["Date Issued",date(d.date_issued)],["Date Returned",date(d.date_returned)],["Status",d.status],[rtl?'ملاحظات':'Notes',d.notes||'—']]}/><button className="ne-full">{c.full} →</button>{admin&&<button className="ne-delete" onClick={remove}>{c.remove}</button>}</aside>}
const Properties=({title,rows})=><section className="ne-properties"><h3>{title}</h3><dl>{rows.map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl></section>;
function Module({title,lang}){return <div className="ne-page"><PageHead title={title} text={lang==='ar'?'سيظهر هذا المجال بعد ربط نموذج البيانات وسير العمل الخاص به.':'This area becomes available after its data model and workflow are configured.'}/><section className="ne-module-state"><b>{lang==='ar'?'الوحدة غير مفعلة':'Module not enabled'}</b><p>{lang==='ar'?'لم نعرض إجراءات شكلية هنا. يلزم إعداد الصلاحيات ومصدر البيانات قبل بدء العمليات.':'No placeholder actions are shown. Configure permissions and a data source before starting operations.'}</p></section></div>}
function Admin({c,users,settings,audit}){return <div className="ne-page"><PageHead title={c.admin} text="Organization, access, integrations, and governance."/><div className="ne-admin"><button onClick={users}><span><b>Users and access</b><small>Accounts, roles, scopes, and authentication</small></span>→</button><button onClick={settings}><span><b>Integrations</b><small>External services and synchronization</small></span>→</button><button onClick={audit}><span><b>Audit explorer</b><small>System activity and change history</small></span>→</button></div></div>}

