import { useCallback, useEffect, useMemo, useState } from 'react';
import Head from 'next/head';
import { useAuth } from '../components/AuthContext';
import LoginPage from '../components/LoginPage';
import DeviceModal from '../components/DeviceModal';
import UsersPanel from '../components/UsersPanel';
import SettingsPanel from '../components/SettingsPanel';
import AuditLogPanel from '../components/AuditLogPanel';
import AccountSettings from '../components/AccountSettings';
import { T } from '../lib/data';
import { getDevices, addDevice, updateDevice, deleteDevice, getAuditLog, addAuditEntry } from '../lib/db';
import { exportExcel } from '../lib/export';

const labels={
 ar:{workspace:'مساحة العمل',assets:'الأصول',operations:'العمليات',procurement:'المشتريات',contracts:'العقود',insights:'التقارير',admin:'الإدارة',search:'ابحث عن أصل، مستخدم، موقع أو عقد',create:'إنشاء',workQueue:'قائمة العمل',workHint:'الأعمال التي تتطلب تدخلك مرتبة حسب الأولوية',priority:'الأولوية',work:'العمل',related:'السجل المرتبط',owner:'المسؤول',due:'الاستحقاق',critical:'حرج',high:'مرتفع',medium:'متوسط',review:'مراجعة',registry:'سجل الأصول',records:'سجل',newAsset:'أصل جديد',view:'العرض',activeView:'أصول الشبكة النشطة',filter:'تصفية',columns:'الأعمدة',asset:'الأصل',tag:'رمز الأصل',category:'الفئة',lifecycle:'دورة الحياة',operational:'التشغيل',assigned:'المستلم',location:'الموقع',seen:'آخر ظهور',risk:'المخاطر',deployed:'قيد التشغيل',stock:'في المخزون',maintenance:'تحت الصيانة',healthy:'سليم',attention:'يحتاج متابعة',selected:'محدد',assign:'تعيين',move:'نقل',change:'تغيير الحالة',export:'تصدير',details:'تفاصيل الأصل',identity:'الهوية',responsibility:'المسؤولية الحالية',activity:'النشاط الأخير',full:'فتح السجل الكامل',edit:'تعديل',remove:'حذف',noResults:'لا توجد نتائج تطابق العرض الحالي',clear:'مسح التصفية'},
 en:{workspace:'Workspace',assets:'Assets',operations:'Operations',procurement:'Procurement',contracts:'Contracts',insights:'Insights',admin:'Administration',search:'Search assets, people, locations, or contracts',create:'Create',workQueue:'Work queue',workHint:'Items requiring your attention, ordered by priority',priority:'Priority',work:'Work item',related:'Related record',owner:'Owner',due:'Due',critical:'Critical',high:'High',medium:'Medium',review:'Review',registry:'Asset registry',records:'records',newAsset:'New asset',view:'View',activeView:'Active network assets',filter:'Filter',columns:'Columns',asset:'Asset',tag:'Asset tag',category:'Category',lifecycle:'Lifecycle',operational:'Operational',assigned:'Assigned to',location:'Location',seen:'Last seen',risk:'Risk',deployed:'Deployed',stock:'In stock',maintenance:'Under maintenance',healthy:'Healthy',attention:'Attention',selected:'selected',assign:'Assign',move:'Move',change:'Change state',export:'Export',details:'Asset details',identity:'Identity',responsibility:'Current responsibility',activity:'Recent activity',full:'Open full record',edit:'Edit',remove:'Delete',noResults:'No records match the current view',clear:'Clear filters'}
};

const Icons=({name})=>{const p={workspace:<><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></>,assets:<><path d="M4 7.5 12 3l8 4.5v9L12 21l-8-4.5z"/><path d="m4 7.5 8 4.5 8-4.5M12 12v9"/></>,operations:<><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></>,procurement:<><path d="M3 5h2l2 11h11l2-8H6"/><circle cx="9" cy="20" r="1"/><circle cx="17" cy="20" r="1"/></>,contracts:<><path d="M6 3h9l4 4v14H6z"/><path d="M14 3v5h5M9 12h7M9 16h7"/></>,insights:<path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/>,admin:<><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></>,search:<><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,plus:<path d="M12 5v14M5 12h14"/>,bell:<><path d="M18 9a6 6 0 0 0-12 0c0 6-3 6-3 8h18c0-2-3-2-3-8"/><path d="M10 21h4"/></>,filter:<path d="M4 5h16l-6 7v6l-4 2v-8z"/>,columns:<><rect x="3" y="4" width="18" height="16"/><path d="M9 4v16M15 4v16"/></>,refresh:<><path d="M20 6v5h-5"/><path d="M18 16a8 8 0 1 1 1-7"/></>,more:<><circle cx="5" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="19" cy="12" r="1" fill="currentColor"/></>,close:<path d="m6 6 12 12M18 6 6 18"/>};return <svg viewBox="0 0 24 24" aria-hidden="true">{p[name]}</svg>};

const jobs=[{p:'critical',ar:'مراجعة أجهزة أساسية انتهى ضمانها',en:'Review core devices with expired coverage',r:'Core infrastructure',o:'Network Operations',d:'متأخر يومين'},{p:'high',ar:'مطابقة 18 جهازًا اكتشفها مسح الشبكة',en:'Reconcile 18 devices found by discovery',r:'Riyadh HQ discovery',o:'Badr',d:'اليوم'},{p:'medium',ar:'استكمال بيانات مركز التكلفة لـ 12 أصلًا',en:'Complete cost center data for 12 assets',r:'Finance reconciliation',o:'Asset Control',d:'12 Sep'}];

export default function NetExpert(){
 const {user,ready}=useAuth(); const [lang,setLang]=useState('ar'),[page,setPage]=useState('workspace'),[devices,setDevices]=useState([]),[audit,setAudit]=useState([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[selected,setSelected]=useState([]),[inspect,setInspect]=useState(null),[modal,setModal]=useState(false),[editing,setEditing]=useState(null),[usersOpen,setUsersOpen]=useState(false),[auditOpen,setAuditOpen]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[accountOpen,setAccountOpen]=useState(false),[sheetsUrl,setSheetsUrl]=useState('');
 const c=labels[lang],t=T[lang],rtl=lang==='ar',admin=user?.role==='admin';
 const load=useCallback(async()=>{setLoading(true);const[d,a]=await Promise.all([getDevices(),getAuditLog()]);setDevices(d||[]);setAudit(a||[]);setLoading(false)},[]);
 useEffect(()=>{if(user)load()},[user,load]); useEffect(()=>{if(typeof window!=='undefined')setSheetsUrl(localStorage.getItem('ne_sheets_url')||'')},[]);
 const rows=useMemo(()=>devices.filter(d=>{const q=search.toLowerCase();return !q||[d.name,d.serial,d.employee,d.empId,d.location,d.type].some(v=>String(v||'').toLowerCase().includes(q))}),[devices,search]);
 const save=async form=>{const old=editing,result=old?await updateDevice(form):await addDevice(form);setDevices(p=>old?p.map(x=>x.id===result.id?result:x):[result,...p]);const e={time:new Date().toISOString(),action:old?'edited':'added',deviceName:result.name,deviceId:String(result.id),oldVal:old?.name||'',newVal:result.name,userName:user.name||user.username,userEmail:user.email||''};const saved=await addAuditEntry(e);setAudit(p=>[...p,saved]);setInspect(result);setEditing(null)};
 const remove=async d=>{if(!confirm(t.confirmDelete))return;await deleteDevice(d.id);setDevices(p=>p.filter(x=>x.id!==d.id));setInspect(null)};
 if(!ready)return null;if(!user)return <LoginPage t={t}/>;
 const nav=['workspace','assets','operations','procurement','contracts','insights'];
 return <div className="ne-app" dir={rtl?'rtl':'ltr'}><Head><title>Net Expert — Asset Operations</title></Head>
  <aside className="ne-sidebar"><div className="ne-org"><b>NE</b><span><strong>Net Expert</strong><small>Enterprise workspace</small></span></div><nav>{nav.map(n=><button key={n} className={page===n?'active':''} onClick={()=>setPage(n)}><Icons name={n}/><span>{c[n]}</span>{n==='operations'&&<em>3</em>}</button>)}{admin&&<button className={page==='admin'?'active':''} onClick={()=>setPage('admin')}><Icons name="admin"/><span>{c.admin}</span></button>}</nav><div className="ne-saved"><p>{rtl?'العروض المحفوظة':'Saved views'}</p><button onClick={()=>{setPage('assets');setSearch('Cisco')}}>Core network <span>6</span></button><button onClick={()=>setPage('assets')}>Warranty ending <span>3</span></button></div><button className="ne-profile" onClick={()=>setAccountOpen(true)}><i>{(user.name||user.username).slice(0,2).toUpperCase()}</i><span><strong>{user.name||user.username}</strong><small>{admin?'Administrator':'Viewer'}</small></span><Icons name="more"/></button></aside>
  <section className="ne-main"><header className="ne-top"><div className="ne-crumb">Net Expert <span>/</span> <b>{c[page]}</b></div><label className="ne-search"><Icons name="search"/><input value={search} onChange={e=>setSearch(e.target.value)} onFocus={()=>setPage('assets')} placeholder={c.search}/><kbd>Ctrl K</kbd></label><button className="ne-primary" onClick={()=>{setEditing(null);setModal(true)}}><Icons name="plus"/>{c.create}</button><button className="ne-icon" onClick={()=>setAuditOpen(true)}><Icons name="bell"/></button><button className="ne-lang" onClick={()=>setLang(x=>x==='ar'?'en':'ar')}>{lang==='ar'?'EN':'ع'}</button></header>
   <main>{page==='workspace'?<Workspace c={c} lang={lang} devices={devices} audit={audit} openAssets={()=>setPage('assets')} openAudit={()=>setAuditOpen(true)}/>:page==='assets'?<Registry c={c} t={t} rtl={rtl} rows={rows} loading={loading} selected={selected} setSelected={setSelected} inspect={inspect} setInspect={setInspect} admin={admin} refresh={load} add={()=>{setEditing(null);setModal(true)}} edit={d=>{setEditing(d);setModal(true)}} remove={remove}/>:page==='admin'?<Admin c={c} users={()=>setUsersOpen(true)} settings={()=>setSettingsOpen(true)} audit={()=>setAuditOpen(true)}/>:<Module c={c} lang={lang} title={c[page]}/>}</main>
  </section>
  {modal&&<DeviceModal t={t} device={editing} onSave={save} onClose={()=>{setModal(false);setEditing(null)}} sheetsUrl={sheetsUrl}/>}
  {usersOpen&&<UsersPanel t={t} onClose={()=>setUsersOpen(false)}/>}
  {auditOpen&&<AuditLogPanel t={t} log={audit} onClose={()=>setAuditOpen(false)}/>}
  {settingsOpen&&<SettingsPanel t={t} sheetsUrl={sheetsUrl} onSave={u=>{setSheetsUrl(u);localStorage.setItem('ne_sheets_url',u)}} onClose={()=>setSettingsOpen(false)}/>}
  {accountOpen&&<AccountSettings t={t} onClose={()=>setAccountOpen(false)}/>}
 </div>
}

function Workspace({c,lang,devices,audit,openAssets,openAudit}){const offline=devices.filter(d=>!d.online).length,damaged=devices.filter(d=>d.status==='damaged').length,unassigned=devices.filter(d=>!d.employee).length;return <div className="ne-page"><PageHead title={c.workspace} text={lang==='ar'?'الأعمال المسندة إليك والتغييرات التي تحتاج متابعة.':'Assigned work and changes requiring your attention.'}/><div className="ne-brief"><b>{lang==='ar'?'ملخص التشغيل':'Operational brief'}</b><p>{lang==='ar'?`يوجد ${offline+damaged} أصلًا يحتاج متابعة تشغيلية. راجع الأولويات قبل بدء الأعمال المجدولة.`:`${offline+damaged} assets require operational attention. Review priorities before scheduled work.`}</p><button onClick={openAssets}>{lang==='ar'?'مراجعة الأصول':'Review assets'} →</button></div><div className="ne-grid"><section className="ne-panel"><PanelHead title={c.workQueue} text={c.workHint}/><JobTable c={c} lang={lang}/></section><aside className="ne-context"><h2>{lang==='ar'?'سياقي':'My context'}</h2><Context label={lang==='ar'?'مسند إليّ':'Assigned to me'} value="8"/><Context label={lang==='ar'?'بانتظار موافقتي':'Awaiting approval'} value="4"/><Context label={lang==='ar'?'متأخر':'Overdue'} value="2" danger/><h3>{lang==='ar'?'آخر التغييرات':'Recent changes'}</h3>{[...audit].reverse().slice(0,4).map((a,i)=><button key={i} onClick={openAudit}><b>{a.deviceName||'System record'}</b><small>{a.userName}</small></button>)}</aside></div><section className="ne-panel ne-condition-panel"><PanelHead title={lang==='ar'?'حالة السجل':'Registry condition'} text={lang==='ar'?'الأصول التي تحتاج قرارًا، وليس إجمالي الأرقام.':'Records requiring a decision, not headline totals.'}/><div className="ne-conditions"><Condition value={offline} label={lang==='ar'?'أصول غير متصلة':'Offline assets'} note={lang==='ar'?'تحتاج تحققًا من حالة التشغيل':'Require verification'}/><Condition value={damaged} label={lang==='ar'?'أجهزة متضررة':'Damaged equipment'} note={lang==='ar'?'تحتاج صيانة أو استبدال':'Need maintenance or replacement'}/><Condition value={unassigned} label={lang==='ar'?'أصول بلا عهدة':'Unassigned assets'} note={lang==='ar'?'راجع الموقع والمسؤولية':'Review ownership'}/></div></section></div>}
const PageHead=({title,text,action})=><div className="ne-heading"><div><h1>{title}</h1><p>{text}</p></div>{action}</div>;
const PanelHead=({title,text})=><div className="ne-panel-head"><div><h2>{title}</h2><p>{text}</p></div></div>;
function JobTable({c,lang}){return <div className="ne-table-scroll"><table className="ne-table"><thead><tr><th>{c.priority}</th><th>{c.work}</th><th>{c.related}</th><th>{c.owner}</th><th>{c.due}</th><th/></tr></thead><tbody>{jobs.map((j,i)=><tr key={i}><td><span className={'ne-priority '+j.p}>{c[j.p]}</span></td><td><b>{j[lang]}</b></td><td>{j.r}</td><td>{j.o}</td><td>{j.d}</td><td><button>{c.review}</button></td></tr>)}</tbody></table></div>}
const Context=({label,value,danger})=><div className="ne-context-row"><span>{label}</span><b className={danger?'danger':''}>{value}</b></div>;
const Condition=({value,label,note})=><button className="ne-condition"><b>{value}</b><span>{label}<small>{note}</small></span><strong>→</strong></button>;

function Registry({c,t,rtl,rows,loading,selected,setSelected,inspect,setInspect,admin,refresh,add,edit,remove}){const all=rows.length>0&&rows.every(d=>selected.includes(d.id)),toggle=id=>setSelected(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]);return <div className="ne-registry"><PageHead title={c.registry} text={`${rows.length} ${c.records}`} action={admin&&<button className="ne-primary" onClick={add}><Icons name="plus"/>{c.newAsset}</button>}/><div className={'ne-viewbar '+(selected.length?'selection':'')}>{selected.length?<><b>{selected.length} {c.selected}</b><button>{c.assign}</button><button>{c.move}</button><button>{c.change}</button><button onClick={()=>exportExcel(rows,t)}>{c.export}</button><i/><button onClick={()=>setSelected([])}><Icons name="close"/></button></>:<><button className="ne-view"><small>{c.view}</small>{c.activeView}⌄</button><span>{rtl?'الحالة: نشط':'State: Active'} ×</span><i/><button><Icons name="filter"/>{c.filter}</button><button><Icons name="columns"/>{c.columns}</button><button onClick={refresh}><Icons name="refresh"/></button></>}</div><div className="ne-registry-body"><div className="ne-table-scroll ne-assets"><table className="ne-table"><thead><tr><th><input type="checkbox" checked={all} onChange={()=>setSelected(all?[]:rows.map(d=>d.id))}/></th><th>{c.asset}</th><th>{c.tag}</th><th>{c.category}</th><th>{c.lifecycle}</th><th>{c.operational}</th><th>{c.assigned}</th><th>{c.location}</th><th>{c.seen}</th><th>{c.risk}</th></tr></thead><tbody>{loading?<tr><td colSpan="10" className="ne-empty">Loading registry…</td></tr>:rows.length===0?<tr><td colSpan="10" className="ne-empty"><b>{c.noResults}</b></td></tr>:rows.map(d=><tr key={d.id} className={inspect?.id===d.id?'current':''} onClick={()=>setInspect(d)}><td onClick={e=>e.stopPropagation()}><input type="checkbox" checked={selected.includes(d.id)} onChange={()=>toggle(d.id)}/></td><td><b>{d.name}</b><small>{d.serial}</small></td><td className="mono">AST-{String(d.id).padStart(6,'0')}</td><td>{t.deviceTypes[d.type]||d.type}</td><td>{d.status==='new'?c.stock:d.status==='damaged'?c.maintenance:c.deployed}</td><td><i className={'ne-dot '+(d.online?'ok':'warn')}/>{d.online?c.healthy:c.attention}</td><td>{d.employee||'—'}</td><td>{t.locations[d.location]||d.location}</td><td>{d.online?(rtl?'قبل 4 دقائق':'4 min ago'):'—'}</td><td className={d.status==='damaged'?'risk':''}>{d.status==='damaged'?c.high:!d.online?c.medium:(rtl?'منخفض':'Low')}</td></tr>)}</tbody></table></div>{inspect&&<Inspector d={inspect} c={c} t={t} rtl={rtl} admin={admin} close={()=>setInspect(null)} edit={()=>edit(inspect)} remove={()=>remove(inspect)}/>}</div></div>}
function Inspector({d,c,t,rtl,admin,close,edit,remove}){return <aside className="ne-inspector"><header><div><small>{c.details}</small><h2>{d.name}</h2><p>AST-{String(d.id).padStart(6,'0')} · {t.deviceTypes[d.type]||d.type}</p></div><button onClick={close}><Icons name="close"/></button></header><div className="ne-inspector-actions">{admin&&<button className="ne-primary" onClick={edit}>{c.edit}</button>}<button>{rtl?'إنشاء مهمة':'Create work item'}</button><button><Icons name="more"/></button></div>{d.status==='damaged'&&<div className="ne-alert"><b>{rtl?'يتطلب قرارًا':'Decision required'}</b><p>{rtl?'الأصل متضرر ولا توجد مهمة صيانة مرتبطة.':'Damaged asset with no linked maintenance work.'}</p><button>{rtl?'إنشاء طلب صيانة':'Create maintenance order'}</button></div>}<Properties title={c.identity} rows={[[rtl?'الرقم التسلسلي':'Serial',d.serial],[c.category,t.deviceTypes[d.type]||d.type],[c.location,t.locations[d.location]||d.location]]}/><Properties title={c.responsibility} rows={[[c.assigned,d.employee||'—'],[rtl?'الرقم الوظيفي':'Employee ID',d.empId||'—'],[rtl?'أضيف بواسطة':'Added by',d.addedBy||'—']]}/><Properties title={c.activity} rows={[[c.operational,d.online?c.healthy:c.attention],[rtl?'تاريخ الإضافة':'Created',d.addedAt?new Date(d.addedAt).toLocaleDateString(rtl?'ar-SA':'en-US'):'—']]}/><button className="ne-full">{c.full} →</button>{admin&&<button className="ne-delete" onClick={remove}>{c.remove}</button>}</aside>}
const Properties=({title,rows})=><section className="ne-properties"><h3>{title}</h3><dl>{rows.map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl></section>;
function Module({title,c,lang}){return <div className="ne-page"><PageHead title={title} text={lang==='ar'?'مساحة تشغيل موحدة للمهام والقرارات المرتبطة بهذا المجال.':'A unified workspace for domain work and decisions.'} action={<button className="ne-primary"><Icons name="plus"/>{c.create}</button>}/><section className="ne-panel"><PanelHead title={c.workQueue} text={c.workHint}/><JobTable c={c} lang={lang}/></section></div>}
function Admin({c,users,settings,audit}){return <div className="ne-page"><PageHead title={c.admin} text="Organization, access, integrations, and governance."/><div className="ne-admin"><button onClick={users}><span><b>Users and access</b><small>Accounts, roles, scopes, and authentication</small></span>→</button><button onClick={settings}><span><b>Integrations</b><small>External services and synchronization</small></span>→</button><button onClick={audit}><span><b>Audit explorer</b><small>System activity and change history</small></span>→</button></div></div>}
